Incident bucket
cdevents/spec pull request #107
Opened 2023-01-24 15:01 UTC by afrittoli

# Changes

Introduce incident events.
    
TBD: schema and README updates
    
Partially-fixes: #59
    
Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [ ] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [ ] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-01-24 15:55 UTC, afrittoli commented
Reference hackmd: https://hackmd.io/h8DBfgwLQuKR7JyUPy0Xow

2023-01-28 13:32 UTC, randomnoise commented on README.md
>  Handling Events associated with Continuous Deployment activities
Short explanations for `Continuous Deployment Events` and `Continuous Operations` are the same.

IMHO, it can be `Handling Events associated with Continuous Operations activities` or similar to what you wrote in spec.md, it can be `Handling Events associated with the health of the services deployed and running in a specific environment`.

2023-01-28 13:33 UTC, randomnoise commented on README.md
> +### [Continuous Operatorations](./continuous-operations.md)
There is a small typo here, it should be:
```suggestion
### [Continuous Operations](./continuous-operations.md)
```

2023-01-30 10:50 UTC, afrittoli commented on README.md
>  Handling Events associated with Continuous Deployment activities
Thanks, good catch!

2023-02-01 15:34 UTC, e-backmark-ericsson requested changes

2023-02-01 15:34 UTC, e-backmark-ericsson commented on continuous-operations.md
> +| description | `String` | Short, free style description of the incident resolution | "Response time restored below 10ms", "CVE-123 acknowledged as non-exploitable" | |
Is it maybe a bad idea to reuse the field name 'description' here, since it has another semantics for the detected and reported predicates?

2023-02-01 15:34 UTC, e-backmark-ericsson commented on README.md
> +### [Continuous Operations](./continuous-operations.md)
```suggestion
### [Continuous Operations Events](./continuous-operations.md)
```

2023-02-01 15:34 UTC, e-backmark-ericsson commented on continuous-operations.md
> +| tickerURI | `URI` | URI of the ticket |  `example.issues.com/ticket123` | ✅ |
```suggestion
| ticketURI | `URI` | URI of the ticket |  `example.issues.com/ticket123` | ✅ |
```

2023-02-01 15:34 UTC, e-backmark-ericsson commented on schemas/incidentreported.json
> +            "tickerURI"
```suggestion
            "ticketURI"
```

2023-02-01 15:34 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Continuous Operations events are related to the operation of services deployed in target environments, tracking of incidents and their remediation. Incidents, and their resolution, can be detected by
I believe it is better to not introduce a new term here (remediation)
```suggestion
Continuous Operations events are related to the operation of services deployed in target environments, tracking of incidents and their resolution. Incidents, and their resolution, can be detected by a number of different actors, like the end-user, a quality gate, a monitoring system, an SRE through a ticketing system or even the service itself.
```

2023-02-01 15:34 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
What does this mean? Can there be multiple incident.detected events for one incident? And can one incident be resolved by multiple incident.resolved events from different sources?

2023-02-02 13:32 UTC, afrittoli commented on continuous-operations.md
> +This event represents an environment that has been modified.
Thanks, good catch.

About the "cancelled" case - I'm not sure what it means for an incident to be cancelled.
Does it mean that the report was incorrect, or that it was irrelevant to the service, or that it was solved without any further action, or?

We had some discussion about acknowledging incidents that do not require further action (for instance a CVE that cannot be exploited) but I would not call that cancelling. 

My proposal would be to stick to resolved only for now and let systems track further nuances in the custom data. We can discuss whether to introduce new dedicated predicates or attributes for next iteration.

2023-02-02 13:35 UTC, afrittoli commented on continuous-operations.md
> +This event represents an environment that has been modified.
How does this sound

> This event represents an incident that has been resolved, meaning that the situation identified by the incident has been addressed or that it ceased to happen or that it has been acknowledged.

2023-02-02 13:36 UTC, afrittoli commented on schemas/incidentreported.json
> +            "tickerURI"
I did it again... thank you for spotting it!

2023-02-02 13:40 UTC, afrittoli commented on continuous-operations.md
> +| description | `String` | Short, free style description of the incident resolution | "Response time restored below 10ms", "CVE-123 acknowledged as non-exploitable" | |
Yes, I was a bit unsure about this as well. 
It's still a description of what has happened though, in one case the start of the incident, in the other the end of it.
I also though we could just leave this for the `customData` but at the end I would prefer to have a short text description included in most events.

2023-02-02 13:40 UTC, afrittoli commented on continuous-operations.md
> +Continuous Operations events are related to the operation of services deployed in target environments, tracking of incidents and their remediation. Incidents, and their resolution, can be detected by
Thank you!

2023-02-02 13:44 UTC, afrittoli commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
Yes indeed, that is what I meant. I think it would be too hard a requirement to ensure sources of incident events that these events are perfectly unique, so it's up to the consumer of the event to reconcile the data afterwards.
I think in future we might consider even an event dedicated to tracking things like root cause analysis, i.e. some event that describes that a number of different events where associated to the same root cause, and what the solution was.

2023-02-03 08:26 UTC, e-backmark-ericsson commented on continuous-operations.md
> +This event represents an environment that has been modified.
I believe that a "canceled" event could be sent when the identified problem was re-evaluated to not be a problem, without any action or solution. More of a recall than a resolution. But we could maybe use the resolved event for that scenario for now.
I propose to not uses the term "situation" but rather "problem", since that is the term used when describing an incident earlier in this document. I also don't think that "acknowledging" an incident means that it is not a problem anymore, rather that the problem has been acknowledged to be a problem. So I propose something like this:

> This event represents an incident that has been resolved, meaning that the problem identified by the incident has been solved or recalled.

2023-02-03 08:32 UTC, e-backmark-ericsson commented on continuous-operations.md
> +| description | `String` | Short, free style description of the incident resolution | "Response time restored below 10ms", "CVE-123 acknowledged as non-exploitable" | |
Ok. In this case the field could maybe be called "solution" as well. But I'm fine with "description" as well for now.

2023-02-03 08:45 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
Hmm. It sounds like we need to be able to correlate one incident.resolved with multiple incident.detected/reported events, and that is not easily doable when correlating events through common id/source objects only. This would be a lot easier if we used links á la Eiffel instead.
I'm not sure we can handle the case where the resolution to multiple incidents are reported by one resolved event only. Do you see how that could be done? Or should we instead write that each incident detected/reported is expected to be correlate to one and only one incident.resolved?

2023-02-06 21:51 UTC, afrittoli commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
The reason for considering multiple events is related to the knowledge available to the system/person that emits the event; I fail to see how links would directly help with that. We could consider incremental updates of the same "detected" event that could add additional information as it becomes available. In that scenario, links would help as they it would be possible to set links to other incident events as they become available.
This is something we should discuss further, perhaps also in the context of "connecting events".

That said, each system / person must know the ID of the subjects it detects. 
Incidents coming from different systems may have different subject IDs even if it later turns out that they are different manifestations of the same underlying problem.  It would be possible to use the "reported" event to associate different detected events to the same issue, and link the different incidents in that way.

2023-02-07 11:39 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
I understand it wasn't obvious what I meant when saying that links would solve this use case. The thing with the Eiffel event linking is that one event can link to multiple "subject" events (using CDEvents terminology), so that one incident.reported event could link to multiple incident.detected events and one incident.resolved event could link to multiple incident.reported events for example.
We could maybe do something similar in CDEvents without links, by allowing a list or dictionary with multiple subject {ID, source} structures in it to be used as the Object referring the earlier event.

2023-02-07 14:36 UTC, afrittoli commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
What we have today in CDEvents is the subjectID + source tuple (which can be the same across events) and event-specific associations with other subjects, e.g. the deployment with an environment or the incident with an environment.

In my understanding the Eiffel link mechanism adds a number of extra features:
1. the ability to add non-event-specific links i.e. any event can be linked with any other
2. the ability to associate semantics with links: since links are not event specific, the semantic of the link cannot be implied and it must be attached to the link (different kinds of links in Eiffel)
3. the ability for a link to point to another event

Perhaps we could consider introducing these features separately in CDEvents, associated with specific use cases.
For incidents, as you said, we don't necessarily need (3), we could link to subjects instead. Strictly speaking, we don't necessarily need (1) or (2) either, as long as added in the incident event schema an array of associated incidents. 

Maybe we could have the following setup:
- event-specific links point to a subject ID, the link semantic is defined in the definition of the event data model
- non-event-specific-links point to an event ID, the link semantic is defined in the event data

2023-02-08 09:32 UTC, e-backmark-ericsson commented
About the naming of the new bucket. I believe it should be without an 's' in the end. So "Continuous Operation" instead of "Continuous Operations"

2023-02-08 10:20 UTC, m-linner-ericsson requested changes

2023-02-08 10:20 UTC, m-linner-ericsson commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
Same comments for all: Shouldn't this be `uri` instead of `uri-reference`? Main concern is with interoperability, the reader must then know intricate knowledge of the sender e.g. which cluster is it deployed in.

2023-02-08 10:20 UTC, m-linner-ericsson commented on examples/incidentdetected.json
> +      "type": "dev.cdevents.incident.detected.0.1.0-draft",
Maybe not part of this PR but the version in `version` vs `type` is super confusing.

2023-02-08 10:20 UTC, m-linner-ericsson commented on schemas/incidentreported.json
> +  "$id": "https://cdevents.dev/0.2.0-draft/schema/incident-detected-event",
```suggestion
  "$id": "https://cdevents.dev/0.2.0-draft/schema/incident-reported-event",
```

2023-02-08 10:20 UTC, m-linner-ericsson commented on schemas/incidentreported.json
> +            "dev.cdevents.incident.detected.0.1.0-draft"
```suggestion
            "dev.cdevents.incident.reported.0.1.0-draft"
```

2023-02-08 12:24 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
First a comment regarding 1. above. Eiffel has no non-event specific link, except for maybe the "CAUSE" link which is used to tell what earlier event CAUSEd the current occurrence to happen.

Regarding this:

> Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.

Does it mean that `subject.source` can be different in different `incident.resolved` events which intend to relate to the same `incident.detected` event? How does that rhyme with the statement on an `subject.id` only being unique within a specific `subject.source`?

```suggestion
Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
**Note** that if the `subject.source` differs it cannot be guaranteed that the correct `incident.detected` event can
be related as a the `source.id` can only be guaranteed to be unique within a specific `subject.source`.
```

2023-02-08 17:41 UTC, afrittoli commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
Yeah, sorry, that was confusing, with "associated to the same incident" I didn't mean associated to the same "incident id", but more high level with the problem that it's occurring.
Let's say that a SW version with a bug that causes high CPU usage is deployed.

As a consequence of that, the system that monitors resource utilisation sends an incident detected event (source=os-monitoring, id=ab1234) and a periodic performance test could detect response time degradation and send an incident detected event (source=perf-test, id=abc56).

Subsequent analysis may discover that those two events are related as they share the root cause, but, as discussed in the last meeting, we would not have a way to model that in CDEvents, at least in the beginning, other than sending incident reported events for both incidents that link them to the same ticket URI.

2023-02-12 20:32 UTC, afrittoli commented on examples/incidentdetected.json
> +      "type": "dev.cdevents.incident.detected.0.1.0-draft",
Thanks for the feedback @m-linner-ericsson - this is what we agreed in terms of versioning, to have two versions, the event version and the spec version. If you think this is an issue could file and issue? I definitely would prefer not to change this for the upcoming release. What we discussed is that we would give this approach a few release to see how it goes and then revisit.

2023-02-12 20:36 UTC, afrittoli commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
This is how it is defined in the spec https://github.com/cdevents/spec/blob/v0.1.1/spec.md#source-context so not anything defined in this PR.

The initial reason for that is that source is a URI-reference in CloudEvents. I don't think we can enforce a URI here really since not all event sources will have a URI associated, but we could do a better job at describe the format of URI-references - I'm tracking this in https://github.com/cdevents/spec/issues/29

2023-02-12 20:37 UTC, afrittoli commented on schemas/incidentreported.json
> +  "$id": "https://cdevents.dev/0.2.0-draft/schema/incident-detected-event",
Nice catch, thank you!

2023-02-12 20:54 UTC, afrittoli commented on continuous-operations.md
> +This event represents an environment that has been modified.
ok, thank you!

2023-02-12 20:59 UTC, afrittoli commented on schemas/incidentdetected.json
> +        "type": {
Yes, good point, it's not included in any of the events in the other buckets either.
It's in the schemas and the go SDK produces it, but it's not included in the markdowns.
It takes one value per subject, but it's probably good to show it in the table for completeness.

2023-02-12 21:01 UTC, afrittoli commented on schemas/incidentdetected.json
> +        "type": {
The type is already in all schemas, but the other schemas do not include its default value yet.
That I was planning to do, but in a separate PR.

2023-02-12 21:02 UTC, afrittoli commented on schemas/incidentreported.json
> +            "dev.cdevents.incident.detected.0.1.0-draft"
thanks!

2023-02-12 21:02 UTC, afrittoli commented on schemas/incidentreported.json
> +          "default": "dev.cdevents.incident.detected.0.1.0-draft"
fixed

2023-02-12 21:06 UTC, afrittoli commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
I decided to just remove this sentence for now, it doesn't add value right now, is that ok?

2023-02-13 07:59 UTC, m-linner-ericsson commented on schemas/incidentdetected.json
> +        "type": {
I don't think people will read the schemas but the markdown. So if it's not in the markdown I wonder if we can say it exists.

2023-02-13 08:12 UTC, m-linner-ericsson commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
The main reason for my objection about the `uri-reference` was that it allows relative urls. Basically you can have a system with two sources having the same source as they differ on the host which is not part of the `source` field.

Regarding this PR: These are the only events that have uri-reference in the schemas. I would suggest to remove it here an do a PR to add it in all the events. Main motivation for this is to keep the protocol consistent, why have do we have one event with this but not all.

2023-02-13 08:14 UTC, m-linner-ericsson commented on schemas/incidentdetected.json
> +        "type": {
Then I would again vote for not introducing the type here, same reasoning as above.

2023-02-16 09:01 UTC, m-linner-ericsson commented on examples/incidentdetected.json
> +      "type": "dev.cdevents.incident.detected.0.1.0-draft",
Have now created https://github.com/cdevents/spec/issues/112

2023-02-16 11:35 UTC, e-backmark-ericsson requested changes

2023-02-16 11:35 UTC, e-backmark-ericsson commented on README.md
> +### [Continuous Operations Events](./continuous-operations.md)
```suggestion
### [Continuous Operation Events](./continuous-operation.md)
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on continuous-operations.md
> +<!--
Inline with a general comment on this PR, I believe this file name should be changed to continuous-operation.md

2023-02-16 11:35 UTC, e-backmark-ericsson commented on continuous-operations.md
> +linkTitle: "Continuous Operations Events"
```suggestion
linkTitle: "Continuous Operation Events"
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on continuous-operations.md
> +   Continuous Operations Events
```suggestion
   Continuous Operation Events
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on continuous-operations.md
> +# Continuous Operations Events
```suggestion
# Continuous Operation Events
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Continuous Operations events are related to the operation of services deployed in target environments, tracking of incidents and their resolution. Incidents, and their resolution, can be detected by
```suggestion
Continuous Operation events are related to the operation of services deployed in target environments, tracking of incidents and their resolution. Incidents, and their resolution, can be detected by a number of different actors, like the end-user, a quality gate, a monitoring system, an SRE through a ticketing system or even the service itself.
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on spec.md
> +- __[Continuous Operations](continuous-operations.md)__: include events related
```suggestion
- __[Continuous Operation](continuous-operation.md)__: include events related
```

2023-02-16 11:35 UTC, e-backmark-ericsson commented on schemas/incidentdetected.json
> +        "type": {
The general clarification of the `type` field in the `subject` object will be handled in #113 . For this PR I believe it should be implemented as in all existing event types, i.e. without the enum format and default fields set.

2023-02-16 11:35 UTC, e-backmark-ericsson commented on schemas/incidentdetected.json
> +        "type": {
I believe this will also be handled through #113 , but the schemas in this PR should then be similar to all existing schemas, i.e. no enum and no default value and instead set as a required field. This is to make sure we can keep the discussion on each introduced change in its relevant context.

2023-02-16 11:35 UTC, e-backmark-ericsson commented on tools/event-version.sh
> +for doc in core source-code-version-control continuous-integration continuous-deployment; do
```suggestion
for doc in core source-code-version-control continuous-integration continuous-deployment continuous-operation; do
```

2023-02-16 11:37 UTC, e-backmark-ericsson commented on continuous-operations.md
> +Multiple events may be associated to the same incident as well as its resolution, coming from diverse sources.
Yes, that's ok.

2023-02-16 11:43 UTC, e-backmark-ericsson commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
I'd say this PR should align with how the existing schemas look, and aligning the usage or uri/uri-reference should be done in #114

2023-03-03 22:17 UTC, afrittoli commented on schemas/incidentdetected.json
> +        "type": {
I agree other events should be fixed in a separate PR, but I don't see the advantage of doing these new events incompletely and fixing them later, but I can remove it if you're keen on it

2023-03-03 22:36 UTC, afrittoli commented on schemas/incidentdetected.json
> +        "type": {
This is not really a change in the specification - it's what we agreed on and documented.
Anyways, since new events won't really be available until we make a release, I don't mind splitting the implementation of the schema in various PRs if that helps.

2023-03-03 22:40 UTC, afrittoli commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
> About the naming of the new bucket. I believe it should be without an 's' in the end. So "Continuous Operation" instead of "Continuous Operations"

Could you elaborate on why we should remove the "s"?  As far as I can see from searching the internet, the practice is commonly referred to as "continuous operations" with the "s". One example https://www.gartner.com/en/information-technology/glossary/continuous-operations

2023-03-03 22:46 UTC, afrittoli commented
> About the naming of the new bucket. I believe it should be without an 's' in the end. So "Continuous Operation" instead of "Continuous Operations"

Could you elaborate on why we should remove the "s"? As far as I can see from searching the internet, the practice is commonly referred to as "continuous operations" with the "s". One example https://www.gartner.com/en/information-technology/glossary/continuous-operations

2023-03-03 23:29 UTC, afrittoli commented on tools/event-version.sh
> +for doc in core source-code-version-control continuous-integration continuous-deployment; do
Nice catch, thank you!

2023-03-03 23:32 UTC, afrittoli commented on schemas/incidentdetected.json
> +          "format": "uri-reference"
I updated this PR - alternatively we could merge https://github.com/cdevents/spec/pull/116 first, and bring back the URI-reference format here.

2023-03-06 09:54 UTC, e-backmark-ericsson commented on schemas/incidentdetected.json
> +        "type": {
I see your point, Andrea, about the difference between a PR and the release lifecycle. But still I believe we should keep all general changes to on PR for several reasons:
- It is confusing to read the documentation when it is not consistent, regardless of if there is a formal release or not
- Even if we've agreed and documented intended changes, they are not in effect before we've updated the docs. There might be a need to discuss certain aspects further through a dedicated PR, and it could happen that once such a PR is being reviewed we might realize that the decision was not the best, and then it is a lot easier to change it if all is in one PR. 
- It provides better traceability through the PRs if all decided changes are made to all involved docs through the same PR.
- SDKs are probably easier to keep in synch with the protocol if a general change is made to all events at the same time
- The amount of work to do to perform a release will be less if the docs is consistent at all times

2023-03-06 09:59 UTC, e-backmark-ericsson commented on schemas/incidentdetected.json
> +        "type": {
I believe you've updated accordingly in a later commit. Thus resolving this comment again.

2023-03-07 08:47 UTC, e-backmark-ericsson commented
> > About the naming of the new bucket. I believe it should be without an 's' in the end. So "Continuous Operation" instead of "Continuous Operations"
> 
> Could you elaborate on why we should remove the "s"? As far as I can see from searching the internet, the practice is commonly referred to as "continuous operations" with the "s". One example https://www.gartner.com/en/information-technology/glossary/continuous-operations

Well, I actually mostly use the term "continuous operation**s**" myself, but when I google on "continuous operation**s**" and compare it to "continuous operation", the singular version is much more common it seems. And our other buckets are named in singular.

We still have the possibility to change things like this before we reach 1.0, but it will probably hurt a bit if we do so I'd like us to make conscious decisions on names like these.

Let's bring it to our workgroup meeting later today and set it there.

2023-03-07 16:25 UTC, e-backmark-ericsson approved these changes
Decided on workgroup meeting on March 7th to keep the 's'

2023-03-07 16:25 UTC, e-backmark-ericsson commented on README.md
> +### [Continuous Operations Events](./continuous-operations.md)
Decided on workgroup meeting on March 7th to keep the 's'

2023-03-07 16:25 UTC, e-backmark-ericsson commented on continuous-operations.md
> +<!--
Decided on workgroup meeting on March 7th to keep the 's'

2023-03-07 16:25 UTC, e-backmark-ericsson commented on spec.md
> +- __[Continuous Operations](continuous-operations.md)__: include events related
Decided on workgroup meeting on March 7th to keep the 's'

2023-03-08 08:41 UTC, m-linner-ericsson approved these changes

2023-03-09 10:02 UTC, afrittoli commented
Merging as discussed in the working group.

2023-03-09 10:02 UTC, merged