Improve subject fields spec and schema
cdevents/spec pull request #118
Opened 2023-03-10 11:15 UTC by afrittoli

# Changes

Improve the spec of subject fields for all events:
- link id and source to their spec definitions
- add the type, linked to its spec definition
- include the value of the type for each event

Improve the jsonschema by constraining the subject type field to the only valid value for each event.

Since all events have been patched already in
v0.2-draft, there's not need to +1 the version
number again within the same spec release.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-03-10 16:23 UTC, e-backmark-ericsson requested changes

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-deployment.md
> +| type | `String` | See [type](../spec.md#type-subject) | `environment` | |
```suggestion
| type | `String` | See [type](../spec.md#type-subject) | `service` | |
```

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
> +<<<<<<< HEAD
```suggestion
```

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
> +>>>>>>> c555c8e (Improve subject fields spec and schema)
```suggestion
```

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
>  | id    | `Purl` | Uniquely identifies the subject within the source. | `pkg:oci/myapp@sha256%3A0b31b1c02ff458ad9b7b81cbdf8f028bd54699fa151f221d1e8de6817db93427?repository_url=mycr.io/myapp`, `pkg:go
The id field should link to the generic description of it

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
>  | id    | `Purl` | Uniquely identifies the subject within the source. | `pkg:oci/myapp@sha256%3A0b31b1c02ff458ad9b7b81cbdf8f028bd54699fa151f221d1e8de6817db93427`, `pkg:golang/mygit.com/myorg/myapp@23
The id field should link to the generic description of it

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
>  | source | `URI-Reference` | [source](../spec.md#source) from the context | | |
Duplicate field
```suggestion
```

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
>  | change | `object`        | The change (tag, commit, revision) of the repository which was used to build the artifact" | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example
Move this line below the `type` line below

2023-03-10 16:23 UTC, e-backmark-ericsson commented on continuous-integration.md
> +=======
```suggestion
```

2023-03-14 13:46 UTC, afrittoli commented on continuous-deployment.md
> +| id    | `String` | See [id](../spec.md#id-subject)| `1234`, `maven123`, `builds/taskrun123` |
Good catch, thank you!
I replaced all `../spec.md#` with `spec.md#` now.

2023-03-14 13:49 UTC, afrittoli commented on continuous-deployment.md
> +| source | `URI-Reference` | See [source](../spec.md#source-subject) | `staging/tekton`, `tekton-dev-123`|
This table describes the fields of the subject, so the `source` here is that from the subject.
In many cases this will have the same value as the source from the context, which is why it's optional in here.

2023-03-14 13:49 UTC, afrittoli commented on continuous-deployment.md
> +| type | `String` | See [type](../spec.md#type-subject) | `environment` | |
Nice catch, thank you!

2023-03-14 14:03 UTC, afrittoli commented
@randomnoise @e-backmark-ericsson thank you for the reviews! Hopefully I addressed all comments

2023-03-15 14:09 UTC, e-backmark-ericsson approved these changes

2023-03-15 14:10 UTC, merged