Adds "skip" as a new testcaserun finished outcome
cdevents/spec pull request #145
Opened 2023-06-26 17:24 UTC by dan-han-101

# Changes

Adds "skip" to the set of possible outcomes for a testcaserun.finished message. A final outcome of "skip" is common for many test frameworks, so adding it as a possible outcome will improve interoperability.

See further discussion in https://github.com/cdevents/spec/issues/140.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [ ] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [ ] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [ ] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-06-27 05:55 UTC, olensmar approved these changes

2023-06-27 11:23 UTC, e-backmark-ericsson requested changes

2023-06-27 11:23 UTC, e-backmark-ericsson commented on schemas/testcaserunfinished.json
- The version should be changed from 0.1.0 to 0.2.0
- testing-events.md should be updated with the added enum value for the outcome
- Adding `skip` as a value on testSuiteRun.finished should also be considered

2023-06-27 14:02 UTC, dan-han-101 commented on schemas/testcaserunfinished.json
Thanks for the thorough review. 
I'll make these updates!

2023-07-31 09:30 UTC, afrittoli commented
@dan-han-101 Emil will be back from PTO the second week of August - is it ok to wait until then?

2023-08-01 12:52 UTC, dan-han-101 commented
Sure, it's no problem .
Thanks for checking in.

2023-08-15 13:05 UTC, e-backmark-ericsson commented
As mentioned in a comment on #146 I believe we need to gather a common view on what it means that a test cases is skipped vs canceled or aborted. It could be fine to add a `skip` outcome value to testCaseRun.finished, but I don't think it should be used to signal that a testcase execution was never even started.

2023-10-02 21:17 UTC, dan-han-101 commented on testing-events.md
> +
This text is meant to replace the updates in [another open PR](https://github.com/cdevents/spec/pull/146/files#diff-2ce116b8a5e17595f3dd740eacaddc773ceb7a2819a2deeef43bc16e8978259aR19-R24). 

I tried to structure the text as sort of state diagram. 

Please see [this comment](https://github.com/cdevents/spec/issues/140#issuecomment-1678902377). This documentation should align with that comment

2023-11-08 06:55 UTC, e-backmark-ericsson commented on testing-events.md
> +| [`testCaseRun`](#testcaserun)   | The execution of a software testCase         | [`queued`](#testcaserun-queued), [`started`](#testcaserun-started), [`finished`](#testcaserun-finished), [`cancelled
I'm not sure if we want this predicate to be called `canceled` or `cancelled`. How to spell it depends on what native dialect of English you're speaking. See https://www.merriam-webster.com/grammar/canceled-or-cancelled
We might need to make a statement in some of our core docs about whether we aim to follow American or British spelling when such doubts occur.
@afrittoli , what is your view?

2023-11-28 01:24 UTC, dan-han-101 commented on testing-events.md
> +| [`testCaseRun`](#testcaserun)   | The execution of a software testCase         | [`queued`](#testcaserun-queued), [`started`](#testcaserun-started), [`finished`](#testcaserun-finished), [`cancelled
I am open to either spelling. 

Looks like "cancelled" is already being used in this repository, but it's only been in the documentation so far. It hasn't actually been used in the spec before. 
https://github.com/search?q=repo%3Acdevents%2Fspec%20cancelled&type=code

2023-11-28 11:00 UTC, afrittoli commented on testing-events.md
> +| [`testCaseRun`](#testcaserun)   | The execution of a software testCase         | [`queued`](#testcaserun-queued), [`started`](#testcaserun-started), [`finished`](#testcaserun-finished), [`cancelled
I made a search in the repo, spelling both with `en_GB` first and `en_US` then. The former led to `artifact` in the spec, and words like `serialized` and `visualization` in the docs; the latter found `Cancelled` in the docs, so I think `en_US` is the winner. 

@e-backmark-ericsson you are right, we should document this, I'll make a PR.

2024-01-02 21:40 UTC, dan-han-101 commented
@afrittoli - anything else I can do to help land this one? Thanks!

2024-02-08 10:43 UTC, e-backmark-ericsson commented on testing-events.md
> +| [`testCaseRun`](#testcaserun)   | The execution of a software testCase         | [`queued`](#testcaserun-queued), [`started`](#testcaserun-started), [`finished`](#testcaserun-finished), [`cancelled
@dan-han-101 , through #173 all occurrences of 'cancelled' where replaced by 'canceled', so the same should be done for this PR.

2024-02-08 10:50 UTC, e-backmark-ericsson commented on testing-events.md
> +
This update is in line with my statements in that other PR, so from my perspective this comment can be set as resolved.

2024-02-08 10:50 UTC, e-backmark-ericsson commented on schemas/testcaserunfinished.json
> +            "dev.cdevents.testcaserun.finished.0.2.0"
The preliminary version of updated events should always include '-draft' in the end. See https://cdevents.dev/docs/primer/#versioning-of-cdevents for more information and also see #139 for another PR also proposing updates to existing events.

2024-02-08 10:51 UTC, e-backmark-ericsson commented
> @afrittoli - anything else I can do to help land this one? Thanks!

Please make sure all unresolved conversations are sorted out and then resolved: https://github.com/cdevents/spec/pull/145/files#conversations-menu

2024-02-08 11:36 UTC, afrittoli commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
I may miss some context on this change - but it seems to me that if we add dedicated predicates for `skip` and `cancel`, the `finished` event should not include those values, rather the corresponding event should be sent in those cases.

2024-02-08 11:40 UTC, afrittoli commented on testing-events.md
> +- Event Type: __`dev.cdevents.testcaserun.finished.0.2.0`__
Version numbers in between releases must include `-draft` - see https://cdevents.dev/docs/primer/#development-of-a-new-version. When we cut spec release `v0.4.0`, all the versions will be automatically lose their `-draft` suffix.

2024-02-08 11:41 UTC, afrittoli commented on schemas/testcaseruncancelled.json
> +          "default": "dev.cdevents.testcaserun.cancelled.0.1.0"
All versions changed (or new) should include a `-draft`

2024-02-08 17:49 UTC, dan-han-101 commented on schemas/testcaseruncancelled.json
> +          "default": "dev.cdevents.testcaserun.cancelled.0.1.0"
I believe I updated all version strings with the "-draft" suffix. 

Note, this particular case (where the discussion was started) was moved to another file
https://github.com/cdevents/spec/pull/145/files#diff-fd1aeb911d993f23a2a282d29d2af28b339cf6e848d59f69491ed1de95013500R24

as I changed the file name for the "cancelled" to "canceled" switch. 

I'll go ahead an resolve this discussion now.

2024-02-08 17:53 UTC, dan-han-101 commented on schemas/testcaserunfinished.json
> +            "dev.cdevents.testcaserun.finished.0.2.0"
Appended "-draft" to this enum
https://github.com/cdevents/spec/pull/145/files#diff-68ee356bdf55cea4f7ddadd9149c57a415a15c589435e92ab6c5cbbcccfff071R24

And all other new or updated types. 

I'll go ahead and resolve this conversation.

2024-02-08 17:55 UTC, dan-han-101 commented on testing-events.md
> +| [`testCaseRun`](#testcaserun)   | The execution of a software testCase         | [`queued`](#testcaserun-queued), [`started`](#testcaserun-started), [`finished`](#testcaserun-finished), [`cancelled
All instances of "cancelled" should be switched over to "canceled" now. 

I'll go ahead and resolve this discussion now.

2024-02-08 18:04 UTC, xibz commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
My intuition says having separate events for each testing state is not the best. I think having the 3 events for test cases, `started`, `updated`, and `finished` is sufficient, and this `skipped` could just be an enum.

Im trying to understand why a consumer would want to listen for a skipped event, and I haven't been able to think of one, so I wonder if just the enum addition makes the most sense

2024-02-08 18:55 UTC, dan-han-101 commented on schemas/testsuiterunfinished.json
> +                "skip"
Thanks for the heads up. 

Is there a issue or pull request to follow ?

2024-02-08 20:43 UTC, dan-han-101 commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
The context of having both predicates (`skipped` and `canceled`) as well as the new outcome `skip` in the `predicate` stems from the discussion in https://github.com/cdevents/spec/issues/140#issuecomment-1678902377 .

I tried to summarize the expected workflows as part of this pull request. See lines 21-27 above in this file. 

@e-backmark-ericsson - care to weigh in on whether you still feel as if it's best to have the different predicates?

2024-02-08 20:49 UTC, xibz commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
Thanks for the context. I dont think Im 100% sold on it being separate events just yet. The example that was given can be accomplished with an enum.

However, that can be said for all event nouns. So the question is when should something be a dedicated event?

For instance, some of our proposals have updated as a predicate instead of every enum as an event. When is it appropriate to have them separated? It isnt too clear for me at least. For example the test suite, test cases, build, and task events all have outcome. Should these all be events instead?

2024-02-09 19:37 UTC, dan-han-101 commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
I think there are two affordances provided by having a separate predicate event (for testcaserun or any other subject). 

1. You can add more specific information to the distinct event. For example, you could add some additional fields to the *.canceled or *.skipped events like what caused the test to stop or not run respectively. If these fields did not work with a *.finished event, it would be less awkward to have separate events.

2. You may want different events in order to maintain certain constraints. 

For example, let's say we wanted to require that 

every *.finished event is preceded by a *.started or *.queued event . 

In this scenario, when a test is skipped, we could either send a *.started or *.queued event, immediately followed by a *.finished event with the outcome set to `skipped`. Or, we could send a single event event,  *.skipped, which does not violate the constraint mentioned above, because we don't send a finished event at all.

For what it's worth, for our purposes we are OK with just the enum update to the finished event outcome. I am just trying to enumerate the reasons why I suspect a separate event was suggested.

2024-02-12 12:05 UTC, afrittoli commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
Thanks @dan-han-101. In addition to your points (1) and (2), dedicated events can be routed differently by the event bus. If a consumer is only interested in failed tests (to send out a notification), but not in skipped and cancelled ones, having the other two separated means that the filtering can be done in the subscription directly. Otherwise, the consumer shall receive all failed test events and inspect the payload to decide what to do.

That said, as a general rule I would tend to have fewer event types in the beginning and add more as the need arises.

For this PR specifically, my only concern is that if we add new event types for skip and cancel, we should then remove those from the enum used in the failed event.

2024-02-12 15:40 UTC, dan-han-101 commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
OK. How about I do the following ?

- Remove `skip` enum from `testcaserun.finished` and `testcasesuiterun.finished` . 
- Keep the `testcaserun.skipped` type. 

The thought line here is, a skipped test doesn't fall under the umbrella of a finished test. 

- Remove the `testcaserun.canceled` type.

There is already an enum for `cancel` in the `outcome` of the `finished` types.

2024-02-16 12:03 UTC, e-backmark-ericsson commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
I don't think we should remove the `canceled` event type. At least not just yet. There is a separate issue on aligning the subject naming and predicates over all 'activity' type events, such as taskRun, pipelineRun, build, testSuiteRun and testCaseRun through #109 , so let's handle any such changes there and focus on the `skip` part here only.

I do believe that the `skipped` predicate makes sense for activities that have a certain expected hierarchy and when the parent activity includes a hardcoded list of expected sub-activities to be executed. For this PR the parent activity is a testSuite and the sub-activity is a testCase. When a testSuite has a hardcoded list of testCases to be executed within it, a consumer that sees a testSuite.queued or testSuite.started event would expect a certain list of testCase.queued/started to appear on the channel. If the test executor for some reason decides to not queue/start a certain testCase in such a testSuite there should be a way to notify that through an event. In that scenario I'd say a testCase.skipped event should be sent. I also elaborated on that in my earlier comment here: https://github.com/cdevents/spec/issues/140#issuecomment-1678902377

We should probably consider introducing a `skipped` predicate also for taskRun's later on, since they are considered children of a pipelineRun.

2024-02-20 21:31 UTC, dan-han-101 commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
In latest version, I tried to limit the scope of this PR to just adding a testcaserun.skipped.

Let me know what you think.

2024-02-21 06:42 UTC, e-backmark-ericsson reviewed
There are a couple of mentions of the environment property left in example and schema, which I believe should not be there for the skipped event. Apart from that this PR looks ok to me now.

2024-02-21 06:42 UTC, e-backmark-ericsson commented on examples/testcaserun_skipped.json
> +      "environment": {
I believe the `environment` property should not be here for the `skipped` event right?

2024-02-21 06:42 UTC, e-backmark-ericsson commented on schemas/testcaserunskipped.json
> +            "environment": {
I believe the `environment` property should not be here for the `skipped` event right?

2024-02-21 11:17 UTC, afrittoli commented on examples/testcaserun_skipped.json
> +      "environment": {
I think it still makes sense. If the test suite is scheduled to run in an environment, the target environment could be one of the reasons why some of the tests are skipped, so it should still be there.

2024-02-21 11:17 UTC, afrittoli commented on schemas/testcaserunskipped.json
> +            "environment": {
I think it should still be there

2024-02-21 16:38 UTC, xibz approved these changes
@dan-han-101 Thanks for the updates! This looks good :)

2024-02-21 21:12 UTC, dan-han-101 commented on examples/testcaserun_skipped.json
> +      "environment": {
I think the environment could still be a valid value and have some meaningful data. 

The evaluation of whether a test should run or should be skipped is often done on some machine/container etc... so there is often a valid value to use. 

If the skip logic is not trivial and has some condition, like run only on certain types of machines, then it would be helpful to know which environment we tried to run the test on. The data could be set in the `reason` field, but having this structured data seems helpful to me.

2024-02-22 18:30 UTC, dan-han-101 commented on schemas/testsuiterunfinished.json
> +                "skip"
Thanks, i'll watch that pr. 
I'll resolve this conversation now.

2024-02-22 18:33 UTC, dan-han-101 commented on testing-events.md
> +| outcome      | `String (enum)`                                                 | The outcome of the testSuite execution, one of `pass`, `fail`, `cancel`, `error`, `skip` | `pass`
I am going to resolve this conversation now too. 

The only pending questions seem to be on whether `environment` is appropriate for `skipped` events. There are other discussion threads for that topic, so we can discuss that separately.

2024-02-23 15:22 UTC, e-backmark-ericsson commented on schemas/testcaserunskipped.json
> +            "environment": {
@dan-han-101 , I thought it shouldn't since it is not mentioned among available properties in the md file: https://github.com/cdevents/spec/blob/5ae9ad7f049df8da11cb6511be10e7c5cc34b3a7/testing-events.md#testcaserun-skipped

But I'm fine with having it defined also for the `skipped` event as long as the md matches the schema.

2024-02-23 15:23 UTC, e-backmark-ericsson commented on examples/testcaserun_skipped.json
> +      "environment": {
Sure, but please make it consistent with the md doc for the event.

2024-02-23 20:30 UTC, dan-han-101 commented on schemas/testcaserunskipped.json
> +            "environment": {
updated

2024-02-28 20:08 UTC, dan-han-101 commented
Hello.  it looks like this one is now blocked because `all commits need to be signed`. 

I'm not sure what's the best path forward here, as I'm not familiar with signing commits.  

Would it be OK for me to squash all my commits, so that this PR only has a single commit, that I will make sure is signed?

Or is there an easy way to add sign off to old commits?

Or, could someone else merge  this PR, by squashing all commits, and signing the finally commit ?

2024-02-29 12:44 UTC, afrittoli commented
> Hello. it looks like this one is now blocked because `all commits need to be signed`.
> 
> I'm not sure what's the best path forward here, as I'm not familiar with signing commits.
> 
> Would it be OK for me to squash all my commits, so that this PR only has a single commit, that I will make sure is signed?
> 
> Or is there an easy way to add sign off to old commits?
> 
> Or, could someone else merge this PR, by squashing all commits, and signing the finally commit ?

Thanks @dan-han-101, sorry about the extra step 🙏 
I would appreciate it if you could squash the commits and force-push. Alternatively, you can `git rebase -i`, mark all unsigned commits for edit and sign them with `git commit --amend`. Stack exchange suggests doing something like this, which seems reasonable:

```bash
git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD~<# of commits from HEAD you need to update>
```

so, probably in your case, it would be:

```bash
git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD~13
```

and then force-push.

2024-03-04 19:38 UTC, dan-han-101 commented
@afrittoli - I *think* this is ready to land now. Please let me know if anything else is needed from me.

2024-03-05 12:32 UTC, afrittoli approved these changes
Thanks for your contribution and patience, this looks good now!

2024-03-05 12:33 UTC, merged