introduce links to CDEvents
cdevents/spec pull request #155
Opened 2023-08-14 07:15 UTC by xibz

# Changes

This commits introduces the concept of linking events to CDEvents. We
take inspiration from Eiffel for certain components, and also outline
new APIs and use cases.

resolves #151

Signed-off-by: benjamin-j-powell <benjamin_j_powell@apple.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ x] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [x ] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [ ] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [ x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-08-14 07:16 UTC, xibz commented
> Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md?rgh-link-date=2023-08-14T07%3A15%3A40Z#versioning)

@afrittoli One thing that wasn't clear to me was the versioning. Can you explain the process? Since the link looks to 404

2023-08-14 08:43 UTC, e-backmark-ericsson commented
@xibz , looks like the title of this PR has been copied from another PR. Could you please correct that?

2023-08-14 09:55 UTC, olensmar approved these changes

2023-08-14 14:40 UTC, e-backmark-ericsson requested changes

2023-08-14 14:40 UTC, e-backmark-ericsson commented on source-code-version-control.md
> +| description | `String` | Description associated with the change, e.g. A pull request's description | `This PR addresses a fix for some feature`| |
This `description` field should also be mentioned in the `change` table (e.g. on line 61 above).
Also, we want to keep the id, source and type fields together, so please move this new field one step down in the table.

2023-08-14 14:46 UTC, e-backmark-ericsson commented
> > Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md?rgh-link-date=2023-08-14T07%3A15%3A40Z#versioning)
> 
> @afrittoli @e-backmark-ericsson One thing that wasn't clear to me was the versioning. Can you explain the process? Since the link looks to 404. We should fix that as well and document the process.

The versioning of cdevents is documented here: https://cdevents.dev/docs/primer/#versioning
You should step the minor version of the change.created event from 0.1.2 to 0.2.0 and keep the spec version as 0.4.0-draft. It's correct that the $id field in the schema will not be possible to resolve until the new spec version is released (and then all files will be updated to 0.4.0 as part of the release as well)

2023-08-14 15:13 UTC, xibz commented on source-code-version-control.md
> +| description | `String` | Description associated with the change, e.g. A pull request's description | `This PR addresses a fix for some feature`| |
Okay, I think I did that correctly. It's a little odd that it seems to be a complete duplicate of the line I added.

2023-08-14 15:16 UTC, e-backmark-ericsson commented on source-code-version-control.md
> +| description | `String` | Description associated with the change, e.g. A pull request's description | `This PR addresses a fix for some feature`| |
> Okay, I think I did that correctly. It's a little odd that it seems to be a complete duplicate of the line I added.

I do agree on that. We should maybe refactor that in the future because it is a bit hard to grasp, but that is what it looks like today at least.

2023-08-14 15:20 UTC, e-backmark-ericsson requested changes

2023-08-14 15:20 UTC, e-backmark-ericsson commented on source-code-version-control.md
> +| description | `String` | Description associated with the change, e.g. A pull request's description | `This PR addresses a fix for some feature`| |
Nit. This table has one column less than the ones in the events section below, so the last column here should be removed for correct md syntax.
```suggestion
| description | `String` | Description associated with the change, e.g. A pull request's description | `This PR addresses a fix for some feature`|
```

2023-08-14 15:51 UTC, e-backmark-ericsson requested changes
Hmm. I'm a bit confused myself over the structure of the json bodies. New subject specific fields should always be placed within the `content` object in the subject object. The top level properties in a subject should only be `id`, `source`, `type` and `content` for all event types.

2023-08-14 15:51 UTC, e-backmark-ericsson commented on examples/change_created.json
> +    "description": "This PR address a bug from a recent PR",
This should be under `content` below... Next to the repository.

2023-08-14 15:51 UTC, e-backmark-ericsson commented on schemas/changecreated.json
> +        "description": {
Please move this down to be part of the `content` object.

2023-08-14 16:43 UTC, xibz commented on schemas/changecreated.json
> +        "description": {
Oh, what's the top level `id`, `source`, and `type` not doing in `content`?

2023-08-15 06:06 UTC, e-backmark-ericsson commented on schemas/changecreated.json
> +        "description": {
I believe the reasoning is that those fields are identifying the subject itself, while any other fields are considered parameters on the subject identity.

2023-08-15 06:07 UTC, e-backmark-ericsson approved these changes

2023-08-15 06:09 UTC, e-backmark-ericsson commented
The only thing missing on this PR is that the commit needs to be signed.
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2023-08-15 09:08 UTC, xibz commented
> The only thing missing on this PR is that the commit needs to be signed.
[docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

@e-backmark-ericsson done!

2023-08-15 10:10 UTC, merged