Update pull request template with working links
cdevents/spec pull request #156
Opened 2023-08-14 15:17 UTC by xibz

# Changes

A couple links seems to be outdated which results in 404s. This commit addresses that by pointing to the CDEvents primer website with the appropriate sub-links.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [ ] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [ ] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [ ] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-08-14 15:46 UTC, e-backmark-ericsson requested changes

2023-08-14 16:40 UTC, xibz commented on .github/pull_request_template.md
>  - [ ] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
Haha, yea, I was wondering about that link and was super confused by it, but I didn't want to touch it since I had no idea why

2023-08-15 05:59 UTC, e-backmark-ericsson approved these changes

2023-08-15 06:03 UTC, e-backmark-ericsson commented
Almost there, but the commit doesn't seem to be signed. We have a requirement on that all commits merged in cdevents shall be signed.
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2023-08-15 09:09 UTC, xibz commented
@e-backmark-ericsson done!

2023-08-15 10:13 UTC, merged