Update testsuiterunqueued.json to replace url with uri
cdevents/spec pull request #162
Opened 2023-08-25 21:34 UTC by obowersa

# Changes
The testsuiterunqueued schema uses the field url under testsuite. Within the other testsuite run schemas, uri is used. This is also used in the markdown documents.

This change updates the testsuiterunqueued schema to bring it in line with the other testsuite's

This is in relation to: https://github.com/cdevents/spec/issues/160

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Has the [primer doc](https://github.com/cdevents/cdevents.dev/blob/main/content/en/docs/primer/_index.md) been updated if a design decision is involved
- [X] Have the [JSON schemas](https://github.com/cdevents/spec/tree/main/schemas) been updated if the specification changed
- [X] Has spec version and event versions been updated according to the [versioning policy](https://cdevents.dev/docs/primer/#versioning)
- [X] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-08-26 10:52 UTC, olensmar approved these changes
thanks for noticing!

2023-08-26 23:53 UTC, obowersa commented
> thanks for noticing!

No worries! I ended up doing an implementation based on the markdown docs and examples which I then used the schema to validate, just highlighted a couple of small gotchas as a result of coming at it cold

2023-08-28 08:23 UTC, e-backmark-ericsson requested changes

2023-08-28 08:23 UTC, e-backmark-ericsson commented on schemas/testsuiterunqueued.json
> +                "uri": {
Any change to an event schema would need a stepped version of the event. And this is a non-backwards compatible change, so it would require stepping the major version of the event schema.
This might sound picky, since we're not at 1.0 of the spec yet. There might not be any implementations of this schema in production yet, but we cannot really know that, so we'd need to update this the formal way.

Reference: https://cdevents.dev/docs/primer/#versioning-of-cdevents

2023-08-29 15:49 UTC, obowersa commented on schemas/testsuiterunqueued.json
> +                "uri": {
I am completely onboard with being consistent in the approach, regardless of if it's pre 1.x or not, so I appreciate the comment. I don't think it's picky at all!

I'll look to amend the PR once I've got access to a laptop and will reach out with any questions.

2023-09-07 15:43 UTC, obowersa commented on schemas/testsuiterunqueued.json
> +                "uri": {
@e-backmark-ericsson  I think I've updated the version correctly ( 0.4.0-draft ). As this is the first time I've dealt with the version side of things would you be able to review. Thanks!

2023-09-07 16:50 UTC, obowersa commented on schemas/testsuiterunqueued.json
> +                "uri": {
Just noticed I'll need to update the examples, will look to do that later today

2023-09-25 13:05 UTC, afrittoli commented on schemas/testsuiterunqueued.json
> +                "uri": {
Thanks @obowersa!

We version events the the overall spec independently - see https://cdevents.dev/docs/primer/#versioning-of-cdevents. The spec version is so that SDKs/Users may implement a specific version of the spec. 
The event version lets users know if anything changed in a specific event when adopting a new spec version.

The event version was `0.1.0` so a new minor version would be `0.2.0` and a new major version would be `1.0.0`.
There is also a small tool that you can use that will increment the version numbers for you: https://github.com/cdevents/spec/blob/main/tools/event-version.sh#L33C1-L34C1

Adding a new `uri` field is a backward compatible change, but removing `url` is not. Given that we are on `0.x` still, we could just remove `url` and set the version to `v0.2.0-draft`. If we want to be extra nice we could deprecate `url`. We've never deprecated a field before, so we'll need to see if there is a way we can express that in jsonschema that we could use when generating the SDK.

2023-09-25 15:42 UTC, obowersa commented on schemas/testsuiterunqueued.json
> +                "uri": {
Thanks for the feedback @afrittoli , and the per event versioning vs the spec version makes total sense. I'd got myself a bit tripped over on that one.

I'll update the PR with the v0.2.0-draft with the current changes for now. The field deprecitation is a great question and something which I imagine will come up again in the future

2024-02-21 11:28 UTC, afrittoli commented on schemas/testsuiterunqueued.json
> +                "uri": {
@olensmar since the test kube team has implemented this event, what do you think about this change?

2024-04-02 11:52 UTC, e-backmark-ericsson commented
@obowersa could you rebase this PR to the latest main?

2024-04-12 09:13 UTC, afrittoli commented
@obowersa - `main` is now open for v0.5 development - would you like to rebase this PR?

2025-01-13 16:19 UTC, davidB commented
@afrittoli, the rename of fields `url` into `uri` was made as part of #200. So This PR could be closed.

2025-01-27 16:36 UTC, afrittoli commented
Closing as already addressed in #200, thanks @davidB and @obowersa for your PR

2025-01-27 16:36 UTC, closed without merging