Move artifact events to their own file
cdevents/spec pull request #172
Opened 2023-11-26 11:22 UTC by afrittoli

# Changes

This commit contains no functional change to the spec. It moves artifact events to their own file (similar to what we did for testing events), in preparation for further artifact events being added.

Cleaned up some wrong references, left over when moving test events, added both testing and artifact events to spec.md too.

Partially-fixes: #143

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/cdevents.dev/blob/main/content/en/docs/primer/_index.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/cdevents/spec/tree/main/schemas) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://cdevents.dev/docs/primer/#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2023-11-26 11:24 UTC, afrittoli commented on artifacts.md
> +### [`artifact packaged`](examples/artifact_packaged.json)
I'm unsure whether we should keep this one in the build stage instead - this is going to be sent by a build system, not a package artifact, and all other events, while some of them could be sent by a build system, are mainly meant for artifact repositories.

2023-11-27 15:14 UTC, e-backmark-ericsson commented on artifacts.md
> +### [`artifact packaged`](examples/artifact_packaged.json)
Yes, I have similar thoughts. The `packaged` and `signed` predicates belong to the artifact itself, while the `published` and `pulled` belong more to the registry. But at the same time there is nothing saying that a build service couldn't publish artifacts in itself as well. E.g. GitHub Packages could be built within GitHub, pushed within GitHub and pulled from GitHub, so in that example GitHub would be both the builder and registry.

I don't think the buckets should declare what type of tool should send them.

2023-12-04 21:27 UTC, mekhanique commented
Artifact pulled (or quarantined as I prefer because an "existing" but "un-useable" artifact helps to ensure that said "bad artifact" is not accidentally re-proxied/re-deployed) should initiate downstream actions that impact deployments (future or existing) for software and services which identifies said artifact within its SBOMs.  An upstream deployment/release system could monitor for this event and "mark" said software/service un-useable.  Reasons for this could be a high severity security finding such as RCE, a legal (licensing or patent) finding, the artifact becoming un-supported (internally or externally), or any other policy that a company might need to implement within this space, such as not using old major versions of a dependency.

2023-12-04 21:35 UTC, mekhanique commented
Also, I'd suggest an `artifact promoted` event here as well (as most recently mentioned on #143)

2023-12-05 05:00 UTC, afrittoli commented on artifacts.md
> +### [`artifact packaged`](examples/artifact_packaged.json)
I think providing a list on intended or recommend tools helps consumer as it provides additional context.
The list of tool types is not prescriptive.

I see buckets as our future conformance groups, so I think it makes sense to be group events that a tool might send.
It could make sense to have events in more than a group as well. When we start generating the docs, I could imagine having the events "tagged" with groups they belong to and having one markdown page per group like today.

2023-12-05 05:01 UTC, afrittoli commented on artifacts.md
> +### [`artifact packaged`](examples/artifact_packaged.json)
An alternative could be to bring all events to one markdown tile, and show the groups as tags, but that might become harder to parse.

2023-12-05 05:03 UTC, afrittoli commented
> I don't really see why there would need to be an artifact.pulled CDEvent defined. What use case would it serve in a CI/CD context?

Heh, I might want to be notified if a certain artifact is downloaded.

2023-12-05 06:05 UTC, mekhanique commented
Definitely something an auditor would want to know; security/legal + info sec

> On Dec 4, 2023, at 9:03 PM, Andrea Frittoli ***@***.***> wrote:
> 
> 
> I don't really see why there would need to be an artifact.pulled CDEvent defined. What use case would it serve in a CI/CD context?
> 
> Heh, I might want to be notified if a certain artifact is downloaded.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/cdevents/spec/pull/172#issuecomment-1840017140>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAGNZLKMIBM6ZHCVMNRQ2WDYH2TJNAVCNFSM6AAAAAA72ZB5ISVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBQGAYTOMJUGA>.
> You are receiving this because you commented.
>

2024-01-12 14:52 UTC, afrittoli commented on artifacts.md
> +### [`artifact packaged`](examples/artifact_packaged.json)
As discussed, I will remove `artifacts.md` for now and add new events in the CI stage

2024-01-12 14:59 UTC, afrittoli commented
> My $0.02 for what it's worth @e-backmark-ericsson . . .
> 
> Artifact pulled (or quarantined as I prefer because an "existing" but "un-useable" artifact helps to ensure that said "bad artifact" is not accidentally re-proxied/re-deployed) should initiate downstream actions that impact deployments (future or existing) for software and services which identifies said artifact within its SBOMs. An upstream deployment/release system could monitor for this event and "mark" said software/service un-useable. Reasons for this could be a high severity security finding such as RCE, a legal (licensing or patent) finding, the artifact becoming un-supported (internally or externally), or any other policy that a company might need to implement within this space, such as not using old major versions of a dependency.
> 
> While not "best practices" from a pure CD point of view, automated roll-backs are performed based on some of these events in live systems today. Events in this space enable automation to be created that helps streamline processes that use this model today.
> 
> Additionally, a quarantine event could trigger automated dependency update pipelines (such as those that might be done via Dependabot, Update-CLI or as otherwise suggested in #39). That would again streamline the process for companies that need to roll-forward as fast as they can.

Thanks. I renamed "pulled" do "downloaded". I will follow up on the idea of "quarantined" in a separate PR

2024-01-12 14:59 UTC, afrittoli commented
@e-backmark-ericsson @xibz ready for review

2024-01-15 15:07 UTC, e-backmark-ericsson requested changes

2024-01-15 15:07 UTC, e-backmark-ericsson commented on continuous-integration.md
> +The event represents an artifact that has been published and it can be advertised for others to use.
```suggestion
The event represents an artifact that has been downloaded from the registry.
```

2024-01-15 15:07 UTC, e-backmark-ericsson commented on spec.md
> +  take place in different stages of the workflow.
Invalid

2024-01-15 15:07 UTC, e-backmark-ericsson commented on continuous-integration.md
> +- Event Type: __`dev.cdevents.artifact.signed.0.1.0`__
```suggestion
- Event Type: __`dev.cdevents.artifact.signed.0.1.0-draft`__
```

2024-01-15 15:54 UTC, afrittoli commented on continuous-integration.md
> +Continuous Integration (CI) events include the subject and predicates related to CI activities such as building software, producing [artifacts](./artifacts.md) and [running tests](./testing-events.md
Thanks, fixed now

2024-01-15 15:56 UTC, afrittoli commented on continuous-integration.md
> +- Event Type: __`dev.cdevents.artifact.signed.0.1.0`__
This is not a new event and it has not been modified in the PR, so the version should not change.

2024-01-15 15:57 UTC, afrittoli commented on continuous-integration.md
> +The event represents an artifact that has been published and it can be advertised for others to use.
Done

2024-01-15 15:57 UTC, afrittoli commented on continuous-integration.md
> +The `artifact signed` event is typically produced by the artifact registry, but it may also be produced by the build system.
Done

2024-01-15 16:00 UTC, afrittoli commented on spec.md
> +  take place in different stages of the workflow.
Thanks, I merged back CI and artifacts

2024-01-16 07:17 UTC, e-backmark-ericsson commented on continuous-integration.md
> +The `artifact signed` event is typically produced by the artifact registry, but it may also be produced by the build system.
```suggestion
The `artifact published` event is typically produced by the artifact registry, but it may also be produced by the build system.
```

2024-01-16 07:17 UTC, e-backmark-ericsson commented on continuous-integration.md
> +The `artifact downloaded` event is typically produced by the artifact registry, but it may also be produced by the build system.
It's probably more common that a test system or a CI system in general downloads an artifact, than a build system (except for libraries and things to integrate in builds of course)
```suggestion
The `artifact downloaded` event is preferably produced by the artifact registry.
```

2024-01-16 07:17 UTC, e-backmark-ericsson commented on continuous-integration.md
> +The `artifact deleted` event is typically produced by the artifact registry, but it may also be produced by the build system.
```suggestion
The `artifact deleted` event is preferably produced by the artifact registry.
```

2024-01-16 07:17 UTC, e-backmark-ericsson commented on spec.md
> +  integration, testing may take place in different stages of the workflow.
```suggestion
  includes events related to building software artifacts and packaging, releasing and managing software artifacts.
- __[Testing](testing.md)__:
  includes events related to testing. Sometimes part of continuous
  integration. Testing may take place in different stages of the workflow.
```

2024-01-16 11:00 UTC, afrittoli commented on continuous-integration.md
> +The `artifact signed` event is typically produced by the artifact registry, but it may also be produced by the build system.
Fixed

2024-01-16 11:01 UTC, afrittoli commented on continuous-integration.md
> +The `artifact downloaded` event is typically produced by the artifact registry, but it may also be produced by the build system.
Nice suggestion, thank you.

2024-01-16 11:07 UTC, afrittoli commented on spec.md
> +  integration, testing may take place in different stages of the workflow.
I think that "Sometimes part of continuous integration, testing may take place in different stages of the workflow." reads better with the comma as it is currently. Fixed the rest.

2024-01-16 11:23 UTC, e-backmark-ericsson approved these changes

2024-01-16 13:50 UTC, merged