Custom events type
cdevents/spec pull request #185
Opened 2024-02-22 15:06 UTC by afrittoli

# Changes

Add support for CDEvents custom events

As previously discussed in https://hackmd.io/LftfRirGRbKuAcLg9pdOag,
this introduces support for custom events:

- add a schemaURI (https://github.com/cdevents/spec/pull/184)
- add dev.cdeventsx types in spec.md
- add a custom folder which includes
  - README.md with context about custom events
  - registry.md to register external specs
  - schema.json - a common schema for custom events

Fixes: [#168](https://github.com/cdevents/spec/issues/168)

Signed-off-by: Andrea Frittoli

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has the [primer doc](https://github.com/cdevents/cdevents.dev/blob/main/content/en/docs/primer/_index.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/cdevents/spec/tree/main/schemas) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://cdevents.dev/docs/primer/#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2024-03-07 08:31 UTC, xibz commented on custom/README.md
> +Some events however, are very specific to a tool or are not relevant from an interoperability point of view.
So Im trying to understand if it is not for interoperability and is strictly specific to a tool, why may someone want to adhere to the CDEvent spec with custom events? My guess is that they want to be able to reuse existing architecture that is there for CDEvents? Is that the idea?

Another benefit I see is that this does not block someone to wait for CDEvents to adopt something. However, this could potentially get out of control very quickly per tool.

2024-03-07 08:31 UTC, xibz commented on custom/README.md
> +When consuming (parsing) an event with `context.schemaURI`, SDKs MUST fetch the schema defined in `context.schemaURI` and **additionally** validate the event against the supplied schema.
Hmm, some security concerns are here especially if it's just some arbitrary URI. This could definitely be alleviated with verification, but that's a whole different can of worms

2024-03-07 08:31 UTC, xibz commented on custom/README.md
> +### Promoting a Custom CDEvent to Core CDEvent
`Core CDEvent` has a pretty strict meaning with `pipeline` and `task` events being under there. We may opt to choose another word to describe this.
Maybe just `Promoting a Custom CDEvent to a CDEvent`

2024-03-07 08:31 UTC, xibz commented on custom/README.md
> +This situation is not dissimilar from the process of adopting a new, backwards incompatible version of an existing event. Once the new CDEvent is introduced in the spec, newer versions of the SDKs wi
It is a little different in that there's a completely separate event that describes the same thing as a custom event. The tooling and infrastructure consume that event. So the amount of churn to support this new event may be much more than simply updating the SDKs which may vary case by case depending on the custom event. I think we need to call this out or reword this to not make a 1:1 mapping to adopting new/backwards incompatible events.

2024-03-07 08:53 UTC, afrittoli commented on custom/README.md
> +Some events however, are very specific to a tool or are not relevant from an interoperability point of view.
Although some of the events are not relevant for the CDEvents community, other events are. For instance, Harbor wants to adopt CDEvents, but some of its events are not supported by CDEvents. Nonetheless, they want to have a consistent format for sending events, i.e. they should all be in CDEvents format.

2024-03-07 08:55 UTC, afrittoli commented on custom/README.md
> +When consuming (parsing) an event with `context.schemaURI`, SDKs MUST fetch the schema defined in `context.schemaURI` and **additionally** validate the event against the supplied schema.
Yes, good point, we may want to let SDK users specify a list or regex of trusted domains, and skip validation for untrusted ones.

2024-03-07 08:56 UTC, afrittoli commented on custom/README.md
> +### Promoting a Custom CDEvent to Core CDEvent
I will fix this

2024-03-07 09:01 UTC, afrittoli commented on custom/README.md
> +This situation is not dissimilar from the process of adopting a new, backwards incompatible version of an existing event. Once the new CDEvent is introduced in the spec, newer versions of the SDKs wi
A new, backwards incompatible version of the same event may require more than updating the SDK as data may have moved to fields with different names or may not be there anymore, but I agree that a completely different event is more likely to be very different and cause more pain.

What I could add here is that `customData` can be used to ease the transition. If the new event is sent, the old one can be included in custom data until all the relevant data is transitioned to the new event.

2024-03-11 13:21 UTC, e-backmark-ericsson requested changes

2024-03-11 13:21 UTC, e-backmark-ericsson commented on custom/README.md
> +When consuming (parsing) an event with `context.schemaURI`, SDKs MUST fetch the schema defined in `context.schemaURI` and **additionally** validate the event against the supplied schema.
```suggestion
When consuming (parsing) an event with `context.schemaUri`, SDKs are recommended to fetch the schema defined in `context.schemaUri` and validate the event against that schema, unless security concerns dictate otherwise.
```

2024-03-11 13:21 UTC, e-backmark-ericsson commented on custom/README.md
> +This means that producers that adopt the new SDK may have to consider producing both the old and the new events, until all consumers have update to the latest SDK.
```suggestion
This means that producers that adopt the new SDK may have to consider producing both the old and the new events, until all consumers have updated to the latest SDK.
```

2024-03-11 13:21 UTC, e-backmark-ericsson commented on custom/README.md
> +Custom CDEvents can be linked like any other CDEvent, so links may exist between custom CDEvents as well as between a custom CDEvent and a normal CDEvent.
```suggestion
Custom CDEvents can be linked like any other CDEvent, so links may exist between custom CDEvents as well as between a custom CDEvent and a normal CDEvent. Note though, that since custom CDEvents could be limited to a certain bounded context while standard CDEvents could potentially be broadcasted to a wider audience, links from a standard CDEvent to a custom CDEvent might not be possible to resolve in all situations.
```

2024-03-12 09:48 UTC, afrittoli commented on custom/README.md
> +When consuming (parsing) an event with `context.schemaURI`, SDKs MUST fetch the schema defined in `context.schemaURI` and **additionally** validate the event against the supplied schema.
Thanks, I replaced MUST with SHOULD and added the security concerns part.

2024-03-12 10:10 UTC, afrittoli commented on spec.md
> +  - `dev.cdevents.mytool-process.finished`
Done

2024-03-12 10:11 UTC, afrittoli commented on custom/README.md
> +Custom event types exist as a mean to make it easier for tools to adopt CDEvents and provide event producers and consumer with a consistent way to produce and consume events aligned to the CDEvents s
Fixed

2024-03-12 10:31 UTC, afrittoli commented on custom/README.md
> +Custom CDEvents can be linked like any other CDEvent, so links may exist between custom CDEvents as well as between a custom CDEvent and a normal CDEvent.
Thanks, I adapted your suggestion a bit and included it as a note

2024-03-12 10:32 UTC, afrittoli commented on custom/README.md
> +### Promoting a Custom CDEvent to Core CDEvent
Replaced "core" with "standard"

2024-03-12 23:38 UTC, xibz approved these changes
This looks good!

2024-03-13 10:59 UTC, merged