Define every `url` and `viewUrl` field as format `uri`
cdevents/spec pull request #200
Opened 2024-04-07 15:39 UTC by davidB

# Changes

- define every fields `url` and `viewUrl` with `format: "uri"` as proposed in #191 
- as the version of schema was with suffix `-draft`, I didn't update them

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has the [primer doc](https://github.com/cdevents/cdevents.dev/blob/main/content/en/docs/primer/_index.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/cdevents/spec/tree/main/schemas) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://cdevents.dev/docs/primer/#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2024-04-12 09:12 UTC, afrittoli commented
@davidB - `main` is now open for v0.5 development - could you rebase your PR based on top of the updated `main`?
@xibz @obowersa this PR is related to #162 and cleanup/consistency work we plan for v0.5.

2024-10-05 14:35 UTC, davidB commented
@afrittoli The PR is rebased on main.

2024-11-18 16:11 UTC, xibz approved these changes
LGTM

2024-11-18 16:11 UTC, xibz requested changes
We should rename `URL` to `URI`s

2024-11-19 13:57 UTC, davidB commented
> We should rename `URL` to `URI`s

@xibz I renamed every field named `url` into `uri`. But kept `viewUrl` as is.

2024-12-02 16:23 UTC, xibz approved these changes

2024-12-04 15:22 UTC, davidB commented
@xibz / @afrittoli Can you merge the PR (I'm not allowed).

2024-12-04 15:32 UTC, afrittoli approved these changes
Thanks @davidB - the change looks good.
Since all event versions have been bumped already and are currently in `-draft` this looks fine, no further updates required.

2024-12-04 15:32 UTC, merged