Fix consistency with casing
cdevents/spec pull request #242
Opened 2024-11-08 18:22 UTC by xibz

# Changes

The links.md and spec.md files had some residual snake casing that did not get fixed. This commit addresses that

2024-11-08 18:23 UTC, xibz commented
@afrittoli I did notice that in the `custom/README.md` casing was all over the place. I believe that's due to it being unrestricted to any format.

Do we want to enforce casing and formatting for custom events? I think we should, but let's talk about it in the next SIG

2025-01-13 16:15 UTC, davidB requested changes

2025-01-13 16:15 UTC, davidB commented on spec.md
>            "context_id": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
I guess you forgot to search & replace `context_id` by `contextId` in this file.

2025-01-15 19:24 UTC, xibz commented on spec.md
>            "context_id": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
Great catch! Updated :)

2025-01-15 20:59 UTC, davidB approved these changes

2025-01-16 10:23 UTC, afrittoli approved these changes
Thank you!

2025-01-16 10:24 UTC, merged