Reformat the spec root page, add subjects and actions
cdevents/spec pull request #26
Opened 2022-02-11 11:05 UTC by afrittoli

Restructure a the spec root page, add more sections and introduce
the initial terminology, including subjects and actions.

This provides the basis for restructuring the vocabulary and
defining the schemas that will be used to build the SDKs.

Partially addresses: #12
Related to: #11

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

2022-02-11 11:08 UTC, afrittoli commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
Alternative names could be services vs jobs (or batches) - other idea? Does this distinction make sense?
I introduced these two groups as I think they have similar properties in terms of actions that are associated to them.

2022-02-11 11:10 UTC, afrittoli commented on spec.md
> +## Context
I have not added anything to the common context for now. If we agree on the subject name, I will add a "subject id" as part of the optional context.
The context will also be expanded with links based on https://github.com/cdevents/spec/issues/10 and as discussed in the WG, but I will setup a dedicated PR for that.

2022-02-11 15:09 UTC, erkist commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
Maybe "which are the occurrences for which events are sent."

2022-02-11 15:09 UTC, erkist commented on spec.md
> +The *subjects* are grouped, for easiness of consultation, in different buckets,
What does "consultation" mean in this context?

2022-02-11 19:59 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
Uhm, that's what I was trying to express in L47 :)
I was debating about only including deltas from the `CloudEvents` spec, but I though I didn't want to create that kind of dependency, so attribution would be enough. I can make more clear in L50.

2022-02-11 20:01 UTC, afrittoli commented on spec.md
> +aware of CDEvent, an external producer creates the CDEvent on behalf of
Nice catch, thank you

2022-02-11 20:02 UTC, afrittoli commented on spec.md
> +A "subject" is the part of a software system that is involved in an occurrence.
That sounds nice :) 
I was debating between the terms "subject" and "entity" - I picked "subject" to align better to CloudEvent, but entity is also a valid candidate. Wdyt?

2022-02-11 20:07 UTC, afrittoli commented on spec.md
> +The *subjects* are grouped, for easiness of consultation, in different buckets,
Oh, that's an "italianism", good catch, thank you. 
One of the meanings of "consultare" in italian is to look into a manual or reference book of any kind for a specific piece of information. Not sure what the best english word for that would be... any suggestions?

2022-02-11 20:13 UTC, afrittoli commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
Thanks! I think I mean to say "which are the "actions" - i.e. "started" and "finished" are actions.
I'm not sure if "actions" is the best term here, I'm open to further ideas.

To expand on the example of the build, the occurrence would be that an artefact build was completed.
Several events could be associated to this occurrance:

event type | subject | action
-----------|--------|---------
dev.cdevents.build.finsihed | build | finished
dev.cdevents.artifact.packaged | artifact | packaged

2022-02-14 10:33 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
The list below is not meant to be only a list of borrowed terms - subject and action for instance are not defined in CloudEvents, and some of the terms have been adapted to CDEvents. 
What I could do is, for the terms that are identical, link the original definition on CloudEvents side.
I didn't go down that route though because we might want to change definitions over time.

2022-02-14 10:46 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
Does this sound better?

> __Note__: CDEvents adopts, wherever applicable, the terminology used by
[CloudEvents](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#notational-conventions). Some of the definitions below are borrowed
from that specification.

2022-02-14 11:08 UTC, afrittoli commented on spec.md
> +The *subjects* are grouped, for easiness of consultation, in different buckets,
I changed it to "to help browsing the spec"

2022-02-14 17:19 UTC, m-linner-ericsson reviewed
Thanks for starting this! Had a couple of concerns.

2022-02-14 17:19 UTC, m-linner-ericsson commented on spec.md
> +### Action
Same there this is level 3. Is that correct?

2022-02-14 17:19 UTC, m-linner-ericsson commented on spec.md
> +- The [*vocabulary*](vocabulary), which identifies *activities*, their
This is the only place we talk about activities. Was this intended?

2022-02-14 17:23 UTC, m-linner-ericsson commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
Aren't we talking about "states" here? 
> What state is the artifact in now? It is packaged.

2022-02-14 17:25 UTC, m-linner-ericsson commented on spec.md
> +This specification defines the following terms:
As I noted in my comments I was a bit confused on where the terms ended. Could we just link to the terminology for CloudEvents or does it help the reader keeping it on this page? What would happen if CloudEvents changes it?

2022-02-14 21:05 UTC, afrittoli commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
Fair point, but not necessarily continuous operations - there are examples in the existing events - specifically environments and services.

2022-02-14 21:09 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
Heh, nice catch, the title level on "subject" or "action" is one too much :) I will fix that.

We could not just link to the terminology for `CloudEvents` because it's not an 100% match - `CloudEvents` terms are more focused on routing, while CDEvents are more focused on the data part and its semantics.

2022-02-14 21:12 UTC, afrittoli commented on spec.md
> +A "subject" is the part of a software system that is involved in an occurrence.
The reason I was proposing "subject" it's because it corresponds to the "subject" defined by CloudEvents, so I didn't want to use two different terms for the same thing. 
On CDEvents side the subject is reacher though, and only its ID will end up in the CloudEvents subject, so perhaps it makes sense to have a different name. 
I'm happy to switch to "entity" if the team is happy with that name. 
We can still changes it in a 0.2 if needed.

2022-02-14 21:18 UTC, afrittoli commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
I see your point, but it's not necessarily a state - if a PR is updated, the event will say "updated" but the PR state will still be "open". I would like to avoid giving the impression that we want to model a state machine through events.
That said, I'm not 100% happy with the term "action" as it's not fitting in all cases either. It is closes though the the idea that we're modelling an occurrence, which is not necessarily a "state transition".

2022-02-14 21:37 UTC, afrittoli commented on spec.md
> +The vocabulary defines *subjects*, their associated *actions* and *fields*.
> I get the idea of introducing some abstract concept but I don't know if it smart to use the word _subject_ as we have a field for it. I think it will become too confusing for the reader.

I don't see how it would be confusing - the subject field will host what I was calling "subject" so it seems fitting?
That said, I'm not necessarily advocating for _subject_ - _entity_ or _activity_ seem like valid alternatives.
I think _entity_ is more generic, _activity_ doesn't seem fitting in some cases.

> 
> Also I not sure about the word _action_ it could be confused with something that should be done. It sound more like you are trying to describe states here. If a build is started or finished the events reflect the changes in the state. However I am not 100% sure about states.

I agree that _action_ may not be the best selection, I was not too happy with it myself. I'm a bit opposed to _state_ though, I don't think it would always be fitting and I would like avoid giving the impression that we're modelling state machines.

> 
> In the introduction we talk about activates. Maybe we could talk about activities and the state of the activities? However that might not be logical for all events. E.g. I don't know if we could call Artifact an activity? On the other side if we connect this to the work done in SIG interopt where we define steps and stages we could tie each event to one step and then say that this events represents an activity in the pipeline.

Yeah, I think _activities_ might be an option, it might be confusing at times. 
I would be happy to consider an "artifact published" as an activity, but I would not say "artifact" is an activity either.

I see a few options (perhaps more):

Artifact Published  | Artifact | Published | dev.cdevents.artifact.published
-------------------|---------|-----------|---------------------------------
Event                       | subject | action       | event type
Event                       | activity  | details      | event type
Activity                    | entity    | (no name) | event type 

This made me think about whether we want the event type to be part of the general CDEvent spec or if it should be specific to the CloudEvents binding alone.

2022-02-14 21:41 UTC, afrittoli commented on spec.md
> +The groups (or buckets) defined are:
Sure, thanks for pointing this out, it seems fitting. I will update this.
We can still move evens around from one stage to another if required to better align with stages. 
I wonder where something like tests would belong. I guess typically the CI stage, but one could have tests running in other states too? The same would be true with bucket anyways.

2022-02-14 21:42 UTC, afrittoli commented on spec.md
> +### Subject
upz, wrong level, I will fix it

2022-02-14 21:42 UTC, afrittoli commented on spec.md
> +### Action
upz, wrong level, I will fix it

2022-02-14 21:43 UTC, afrittoli commented on spec.md
> +- The [*vocabulary*](vocabulary), which identifies *activities*, their
I forgot to update this, but we can also keep the "activity" term, we just need to clarify what it means.

2022-02-15 10:05 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
So, finally I included links to terms which are borrowed from CloudEvents, I hope that make things clearer :) 
Thanks for the feedback on this

2022-02-15 13:48 UTC, erkist commented on spec.md
> +A "subject" is the part of a software system that is involved in an occurrence.
I am fine with "subject". Entity is both a bit vague and a bit overused in my opinion. Like "node". What the heck is a "node".

2022-02-15 13:54 UTC, erkist commented on spec.md
> +The vocabulary defines *subjects*, their associated *actions* and *fields*.
I like the Event:subject:action best.

The only part that causes a little bit of dissonance in my thoughts is that subject has two meanings in my head: 1. An entity that something is being done to, and 2. "Topic title" (as in subject vs. body in an e-mail).

But I still like it best.

2022-02-15 16:19 UTC, m-linner-ericsson commented on spec.md
> +This specification defines the following terms:
Nice, just one question. Why not keep this part of the event definition? I think it adds value but there might be something I am missing.

> Events will contain two types of information: the [Event Data](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#event-data) representing the Occurrence and [Context](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#context) metadata providing contextual information about the Occurrence. A single occurrence MAY result in more than one event.

2022-02-15 16:29 UTC, m-linner-ericsson commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
I guess we could have other subjects as *artifact*, *branch*, *repository* and *change*. Where would those fall?

2022-02-15 17:00 UTC, afrittoli commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
I would say those would all be long running

2022-02-15 17:01 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
I think that part may not be fitting for CDEvents - we haven't fully designed it yet, so I didn't want to include it until I was sure how it was going to be.

2022-02-15 17:40 UTC, afrittoli commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
_verb_ or _predicate_ both sounds good to me, thank you!

2022-02-15 23:28 UTC, afrittoli commented on spec.md
> +The groups (or buckets) defined are:
Updated to "stages"

2022-02-15 23:33 UTC, afrittoli commented on spec.md
> +- The [*vocabulary*](vocabulary), which identifies *activities*, their
Done.

2022-02-15 23:34 UTC, afrittoli commented on spec.md
> +A "subject" is the part of a software system that is involved in an occurrence.
Cool, kept *subject* as final term

2022-02-15 23:34 UTC, afrittoli commented on spec.md
> +`finished`, which are the events. The `build` entity has a schema which defines
Updated to use *subject* and *predicate*

2022-02-15 23:35 UTC, afrittoli commented on spec.md
> +## Context
I will add the *subject* in a follow-up PR

2022-02-16 12:22 UTC, e-backmark-ericsson requested changes

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +subject of the occurrence, or when a service is deployed, the subject is the service. Subjects have a schema associated, defined in the
Regarding "Subjects have a schema associated", please see my comments on the Vocabulary below.

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +  example a service or an environment
```suggestion
  example a service, an environment, an artifact or a source change
```
To clarify a bit in accordance with the comments below.

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +A "predicate" is what happens to a subject in an occurrence.
```suggestion
A "predicate" is what happened to a subject in an occurrence.
```
to clarify that the event notifies what has happened and not what is happening.

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
>  - __Event ID__: defines a unique identifier for the event
```suggestion
- __Event ID__: defines a identifier for the event. The Event ID should be unique within the given Event Source.
```

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +The following attributes are REQUIRED to be present in all the Events defined in
Where do we define the _syntax_ of these attributes? I.e. that the Event ID should be a UUID-4 (?) and that the Event Timestamp should have a certain date/time format?

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +which are associated to different parts of a Continuous Delivery Process where
```suggestion
which are associated to different parts of a Continuous Delivery process where
```

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +- The [*context*](context), made of mandatory and optional *fields*, shared by
```suggestion
- The [*context*](context), made of mandatory and optional *attributes*, shared by
```
Should all occurrences of 'field' be replaced with 'attribute' in this spec? Or do they sometimes represent different things?

2022-02-16 12:22 UTC, e-backmark-ericsson commented on spec.md
> +These *subjects*, with their associated *actions* and *fields*, are agnostic
```suggestion
These *subjects*, with their associated *predicates* and *fields*, are agnostic
```

2022-02-16 13:02 UTC, afrittoli commented on spec.md
> +This specification defines the following terms:
Done

2022-02-16 13:04 UTC, erkist commented
Once Emil's changes are considered, you can assume approval from me.

2022-02-16 13:05 UTC, erkist approved these changes

2022-02-16 13:06 UTC, afrittoli commented on spec.md
> +- [*consumer*](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#consumer)
Done

2022-02-16 13:06 UTC, afrittoli commented on spec.md
> +- [*intermediary*](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#intermediary)
Done

2022-02-16 13:15 UTC, e-backmark-ericsson commented on spec.md
> +or `finished`, which are the predicates. The `build` entity has a schema which
```suggestion
or `finished`, which are the predicates. The `build` subject has a sub schema which
```

2022-02-16 13:16 UTC, afrittoli commented on spec.md
> +subject of the occurrence, or when a service is deployed, the subject is the service. Subjects have a schema associated, defined in the
done

2022-02-16 13:17 UTC, afrittoli commented on spec.md
> +A "predicate" is what happens to a subject in an occurrence.
Good catch, thank you

2022-02-16 13:18 UTC, afrittoli commented on spec.md
>  - __Event ID__: defines a unique identifier for the event
Sounds good, only replaced "should" with "MUST"

2022-02-16 13:20 UTC, afrittoli commented on spec.md
> +The following attributes are REQUIRED to be present in all the Events defined in
We don't yet - we lack syntax throughout the spec, so I was going to add that in a follow-up PR to avoid clustering too many changes at once.

2022-02-16 13:20 UTC, afrittoli commented on spec.md
> +which are associated to different parts of a Continuous Delivery Process where
done

2022-02-16 13:21 UTC, e-backmark-ericsson commented on spec.md
> +The following attributes are REQUIRED to be present in all the Events defined in
Fair enough

2022-02-16 13:23 UTC, e-backmark-ericsson commented on spec.md
>  - __Event ID__: defines a unique identifier for the event
Ok

2022-02-16 13:28 UTC, afrittoli commented on spec.md
> +- The [*context*](context), made of mandatory and optional *fields*, shared by
done

2022-02-16 13:28 UTC, afrittoli commented on spec.md
> +These *subjects*, with their associated *actions* and *fields*, are agnostic
done

2022-02-16 14:05 UTC, m-linner-ericsson commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
Sorry but you lost me. How can an artifact be long running? An artifact could be documentation, that is not something that will be run. It could of course be deployed but I wouldn't define it as long running.

Should we instead talk about "permanent subject" and "temporary subject"?
* "Permanent subjects" would have a long lifespan and nothing will wait for it because it will not complete.
* "Temporary subjects" would have a short lifespan that can have things waiting for it as it will complete.

Not sure about "permanent" and "temporary" but I hope you get the idea what I am out after.

If you think it will drag out this PR. Let us take it in another one.

2022-02-16 14:06 UTC, m-linner-ericsson commented on spec.md
> +The vocabulary defines *subjects*, their associated *actions* and *fields*.
I will probably need some examples to fully wrap my head around what your are intending.

2022-02-16 14:09 UTC, m-linner-ericsson commented on spec.md
> +This specification defines the following terms:
ok

2022-02-16 14:09 UTC, m-linner-ericsson approved these changes

2022-02-16 14:09 UTC, e-backmark-ericsson approved these changes

2022-02-16 14:12 UTC, m-linner-ericsson commented
@afrittoli To enable other people outside our group to understand this I think we need full examples of a couple of scenarios. These examples could be based on cloud event bindings.

2022-02-16 14:35 UTC, afrittoli commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
Yeah, that's the issue with the term "long running" - an artefact is not "running", but it continue to exists unless someone takes an explicit action to remove it.

The key differentiator between the two categories is that subjects in the first one naturally runs to completion after performing a job of some kind (taskrun, pipelinerun, build, test), while subjects in the second one will continue to exists unless someone of something takes an action to terminate them (service, environment, artifact).

I'm not quite sure what a good terminology could be for this. 

There a couple of reasons for introducing the two categories:

- events in each category are likely to share predicates
- producers and consumers may expect different set of predicates 
- from a producer point of view, subject that run to completion won't have an explicit trigger when they complete, so setting up links might be challenging in the completion event

Defining the two groups and giving them a name may help reason about their predicates in general.
I created https://github.com/cdevents/spec/issues/27 to track this discussion

2022-02-16 14:49 UTC, m-linner-ericsson commented on spec.md
> +  prevents them from continuing - for example a task run, a build or a test
ok, lets track it there

2022-02-16 14:51 UTC, afrittoli commented
Thanks everyone for the great input on this. I'll go ahead and merge, and start working on the next parts.

2022-02-16 14:51 UTC, merged