Add syntax details for attributes in CDEvents
cdevents/spec pull request #30
Opened 2022-02-21 16:34 UTC by afrittoli

Expand the definition of mandatory attributes by adding syntax
details and examples.

Introduce the "version" as a mandatory attribute.
Add the subject as an optional attribute as discussed in the WG.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

2022-02-22 16:56 UTC, afrittoli commented on spec.md
> +  - OPTIONAL
Should this be MANDATORY to be consistent with the vocabulary where subject is required.

2022-02-23 16:06 UTC, m-linner-ericsson commented on spec.md
> +    ```json
So in Eiffel we have our two events:
* [Activity Triggered](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityTriggeredEvent.md) giving the activity a name, including the possibility to give a category, and also describe how the activity was triggered
* [Activity Started](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityStartedEvent.md) linking back to the *Activity Triggered* but containing the execution URI and links to logs to find more information.

In your example I guess the `id` would be the same as `name` in our *Activity Triggered* event. The `URL` would be the `executionUri` *Activity Started* event. I am trying to figure out how the `task` would map. What would you use it for? The closest thing I can think of is the `categories` filed in the *Activity Triggered* event. Would you say the `task` would be used to group events together?

2022-02-23 20:47 UTC, afrittoli commented on spec.md
> +#### version
The version is not included in the type currently. We're not going to release events independently, so I think it makes sense to have the version as an attribute of the CDEvent

2022-02-23 20:50 UTC, afrittoli commented on spec.md
> +  - MUST be a non-empty string
Each version of the spec will refer to its own version only, link in L156. 
Once we have more than one version, the [docs website](https://cdevents.dev/docs) will include a dropdown with list of available versions.

2022-02-23 21:28 UTC, afrittoli commented on spec.md
> +#### subject
No, the subject will only include attribute which are valid for the subject of the specific event-type. 

For instance, in case of [`environment`](https://cdevents.dev/docs/continuous-deployment-pipeline-events/) events, the subject is an `environment` and will include id, name and URL.

The same `environment` object might show up in other events too, like `service` type of events. The subject there will be the `service` (with its own attributes). The service event will include an attribute `environment` of type `object` as well, which will specify which `environment` the `service` is running in.

My idea is to define the various kind of subjects / objects in the vocabulary once so that they may be re-used then in various events.

2022-02-23 21:38 UTC, afrittoli commented on spec.md
> +    ```json
The `ID` usually represents the unique identifier of the subject within the event source. 
I think all subjects we define will have an `ID`, but this is defined in the vocabulary really.

Subjects will have different attributes, `task` is only valid for `taskrun` for instance. 
The `task` is an identifier of the definition that is executed in the `taskrun`. 
Here I'm just including what we have in the vocabulary today.

In terms "triggered" vs "started" - in CDEvents, they would be `predicates` and - at least for now - they vary event by event. There may be an opportunity to reduce the number of predicates and make them standard across events, but we'll have to see if it works well or not. 

The separation of `subjects` in "long running" and "run to completion" could help create a standard set of `predicates`, one for each group... but it may turn out that it's not actually possible.

2022-02-23 21:39 UTC, afrittoli commented on spec.md
> +          "id": "my-taskrun-123",
Yeah, nice catch. They don't have to match... but in tekton they would :)

2022-02-23 21:40 UTC, afrittoli commented on spec.md
> +          "task": "my-task",
No, there is no naming enforced between tasks and taskruns in Tekton, the taskrun of task "my-task" can be called anything really. That said, it would make sense to fix the URL below to use `my-task` as well :)

2022-02-23 21:42 UTC, afrittoli commented on spec.md
> +          "status": "Running",
Possibly, or it could provide more insight. Again, this matches what we have in the vocabulary today - if we change the vocabulary we need to update these examples accordingly, but for this PR I would not go and touch the vocabulary part

2022-02-23 21:44 UTC, afrittoli commented on spec.md
> +  - OPTIONAL
Fixed

2022-02-23 21:45 UTC, afrittoli commented on spec.md
> +          "task": "my-task",
Fixed

2022-02-23 21:45 UTC, afrittoli commented on spec.md
> +          "id": "my-taskrun-123",
Fixed

2022-02-23 22:03 UTC, afrittoli commented
Thank you @m-linner-ericsson for the thorough review!
I think I either addressed or replied to all your comments.
I expanded on the `source` based on the discussion in the working group and the feedback I got from the CloudEvents folks on slack. I think for now we don't need source to be an `object`- I'd rather have the source being as simple as possible, at least until we hit a use case where we need more.

2022-03-02 09:00 UTC, m-linner-ericsson commented on spec.md
> +  - MUST be a non-empty string
Line 156 in this document?

Was your idea to have state the version as the only valid value?

My idea with a list was for to ease for the reader finding the valid range of version available

2022-03-02 10:05 UTC, m-linner-ericsson commented on spec.md
> +          "status": "Running",
I would not include the `status` field in subject object but only use it to define the subject itself.

2022-03-02 10:11 UTC, m-linner-ericsson commented on spec.md
> +#### subject
If it is just used to define the subject I am ok with it. I was a bit hard to see the pattern when you included the `status` filed.

2022-03-02 10:19 UTC, m-linner-ericsson commented on spec.md
> +    ```json
In Eiffel as we have a triggered event and then link back to it so we don't need to worry about the uniqueness of an ID. So from my view we are talking about:

* `ID`: unique identifier
* `task`: A human friendly display name for the task instance
* `URL`: the link to the task instance 

If I understand correctly it would be more logical if `task` was `Run of my-task #123`

2022-03-02 10:26 UTC, m-linner-ericsson commented
@afrittoli To ease the job of the reviewer it would be nice to have the complete history so you can see what has changed. A humble request would be that, if you want to force push could you force push the branch with all the commits?

2022-03-02 11:45 UTC, afrittoli commented
> @afrittoli To ease the job of the reviewer it would be nice to have the complete history so you can see what has changed. A humble request would be that, if you want to force push could you force push the branch with all the commits?

Yes, sure - I can do that. 

My usual workflow is to force-push because that keeps the git history clean. Unfortunately GitHub, unlike Gerrit, doesn't have a concept of patchsets, only commits, which means that to keep a readable git history one then has to squash the commits into one before merging the PR. Assuming that in most cases we will only have one commit per PR that works relatively well.

2022-03-02 15:52 UTC, e-backmark-ericsson requested changes

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
> +  - MUST be unique within the scope of the producer
```suggestion
  - MUST be unique within the given `source` (in the scope of the producer)
```

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
> +#### type
The event type attribute is currently also defined in each vocabulary stage file, for example here: https://github.com/cdevents/spec/blob/main/core.md?plain=1#L32. Please update those md files as well within this PR so we don't get duplicate definitions of the same attributes.

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
> +  - dev.cdevents.<subject>.<predicate>
These angle brackets don't seem to render well. Should they be escaped?
```suggestion
  - dev.cdevents.\<subject\>.\<predicate\>
```

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
> +  - MUST adhere to the format specified in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339)
Just want to mention this, in case someone wonders:
In Eiffel we define the timestamp using UNIX Epoch time (in milliseconds), and the main reason to that is probably as that makes it easier for a machine to calculate the diff between two events, and since the Eiffel events are not primarily intended for human consumption. I guess the benefit of having human readable timestamps should overrule that though, for CDEvents, since it makes it a lot easier for a human to troubleshoot the events.

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
> +- Description: The version of the CDEvents specification which the event
Have we discussed whether the each event type should have its own versioning lifecycle or if a version should only be set on the full specification? In Eiffel we previously used one version for the full spec but we later changed to defining a version for each event type individually.

2022-03-02 15:52 UTC, e-backmark-ericsson commented on spec.md
There is a mix of markup used in this PR, when it comes to referencing attributes and sections in the document. Some references are encapsulated within back-quotes and some are not. Some references render as active links and some do not. Please streamline that.

2022-03-02 22:45 UTC, afrittoli commented on spec.md
> +#### type
This is already the case - see https://cdevents.dev/docs/spec/. 
I'm just adding more details here.
I will update the vocabulary pages in a separate PR.

2022-03-02 22:45 UTC, afrittoli commented on spec.md
> +  - dev.cdevents.<subject>.<predicate>
Nice catch, thank you

2022-03-02 22:48 UTC, afrittoli commented on spec.md
> +- Description: The version of the CDEvents specification which the event
We discussed in the past but I'm not sure if we came to a conclusion.
Since some parts are common, we'll need a version for them. 
What was the reason for versioning events individually in Eiffel?

2022-03-02 22:53 UTC, afrittoli commented on spec.md
> +  - MUST be a non-empty string
The list of valid version will be listed on top of the documentation, so it should be easy to discover.

The main reason for me is that if I'm browsing a specific version of the spec, I should only use that version in my events. Also I would not like to keep cross-version information in version specific pages.

I'd be happy to include the list of versions in the main README as long as we keep it independent of the versioned docs.

2022-03-02 22:57 UTC, afrittoli commented on spec.md
> +          "status": "Running",
> Ok, then you need to help me. Were do we state in the vocabulary that the should have the status here?

It's in here https://cdevents.dev/docs/core/ but it's only defined for `PipelineRun`, not for `TaskRun`. I didn't realise that, it seems to be incomplete. I can use a `PipelineRun` instead of a `TaskRun` in the example if you want.

2022-03-02 22:59 UTC, afrittoli commented on spec.md
> +          "status": "Running",
> I would not include the `status` field in subject object but only use it to define the subject itself as I guess it will be the same subject object in all events of the same subject disregarding the predicate. For example both `taskrun.started` and `taskrun.finished` would have the same subject object.

Can we discuss the objects in the vocabulary in the next PR once I update those? 
If we change the structure or add/remove fields, I will update this example accordingly.

2022-03-03 13:20 UTC, e-backmark-ericsson commented on spec.md
> +#### type
It's confusing to me that each stage page in the vocabulary has their own definitions of Event Type when it is already defined here. If Event Type should still be defined on each such page it should also include id, source, timestamp, version and subject, right? Isn't it better to update all this in the same PR to keep the docs consistent?

2022-03-03 13:25 UTC, e-backmark-ericsson commented on spec.md
> +- Description: The version of the CDEvents specification which the event
The Eiffel protocol is released in _editions_, which groups all event types together in one set where each event type has its own semver version. One reason of versioning each event individually is that it makes it clear between different editions/releases of the protocol what event types have been updated and not. Also, if a certain event producer/consumer is producing/consuming a certain subset of the events, core events for example, it will not need to be updated just because some non-core events have been updated. So, it decreases the need to update the surrounding systems.

2022-03-03 16:17 UTC, afrittoli commented on spec.md
I think I've addressed this now, let me know if that looks good

2022-03-04 07:22 UTC, e-backmark-ericsson commented on spec.md
The vocabulary section is in some places referenced with back-quotes and sometimes without back-quotes.

2022-03-04 09:29 UTC, m-linner-ericsson commented on spec.md
> +  - MUST be a non-empty string
So your idea was to put the spec version as the only valid field?

Maybe add something like

> MUST be the version of the event/spec used for producing the event

2022-03-04 09:38 UTC, m-linner-ericsson commented on spec.md
> +          "status": "Running",
Ok, so you want to include all the pipeline attributes in the subject object?  From your comment above  I got it that you didn't want to. I would still vote to not include it but if you want to proceed with the PR you can keep it 😄

2022-03-04 09:43 UTC, m-linner-ericsson commented on spec.md
> +    ```json
I think examples are vital for understanding as the subject object is a new concept and it wasn't that easy to follow your train of thoughts. If you want to keep the example here we could go back and change it later. 😄

2022-03-04 11:10 UTC, afrittoli commented on spec.md
> +    ```json
I totally agree that examples are vital! I'll try to make more of them in the next PRs and align these accordingly.

2022-03-04 11:21 UTC, afrittoli commented on spec.md
> +- Description: The version of the CDEvents specification which the event
https://github.com/cdevents/spec/issues/32

2022-03-04 11:33 UTC, e-backmark-ericsson approved these changes

2022-03-04 12:13 UTC, m-linner-ericsson approved these changes

2022-03-04 12:15 UTC, merged