Add introduction to CDEvents
cdevents/spec pull request #34
Opened 2022-03-11 15:55 UTC by m-linner-ericsson

I wanted to create a introduction to CDEvents explaining to a larger audience why we created the project and what it provides. 

I have taken inspiration from previous PR material and other markdown documents, but also added a few idea myself.

If you feel the text should live in another document please feel free suggest that.

Signed-off-by: Mattias Linnér mattias.linner@ericsson.com

2022-03-15 15:13 UTC, e-backmark-ericsson requested changes
I embrace this initiative, and I believe it captures the background well enough as it is now written.

Maybe this page deserves a ToC now as its content has grown quite a lot?

2022-03-15 15:13 UTC, e-backmark-ericsson commented on README.md
> +meaning of an event.
```suggestion
to the event.
```

2022-03-15 15:13 UTC, e-backmark-ericsson commented on README.md
> +By providing a interoperable way of tool to communicate we also provide means to
```suggestion
By providing an interoperable way of tools to communicate we also provide means to
```

2022-03-15 15:13 UTC, e-backmark-ericsson commented on README.md
> +give an overview picture increasing observability, but also provides measuring
```suggestion
give an overview picture increasing observability, but also to give measuring
```

2022-03-15 15:13 UTC, e-backmark-ericsson commented on README.md
> +Using this language we defining a set of events that has purpose and semantic
```suggestion
Using this language we define a set of events with purpose and semantic
```

2022-03-15 15:13 UTC, e-backmark-ericsson commented on README.md
> +* Not scale - when trying to add new consumers or senders each tools have to make
```suggestion
* Not scale - when trying to add new consumers or producers each tool have to make
```

2022-03-18 14:38 UTC, afrittoli commented
> I wanted to create a introduction to CDEvents explaining to a larger audience why we created the project and what it provides.
> 
> I have taken inspiration from previous PR material and other markdown documents, but also added a few idea myself.
> 
> If you feel the text should live in another document please feel free suggest that.
> 
> Signed-off-by: Mattias Linnér [mattias.linner@ericsson.com](mailto:mattias.linner@ericsson.com)

Thanks @m-linner-ericsson !
I think it's nice to provide a little bit more context in the main README. But I would prefer to keep the READM not too busy, and maybe move some of this content to the CDEvents primer?

2022-03-18 14:43 UTC, afrittoli commented on images/stack.drawio
> +<mxfile host="Electron" modified="2022-03-09T14:09:43.285Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/16.5.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/
Thanks for including the source!

2022-03-18 14:44 UTC, afrittoli commented on README.md
> +#### How does it enable tools to communicate in a interoperable way?
Perhaps from this point on we could add this material to the `primer.md` document?

2022-03-18 14:47 UTC, afrittoli commented on README.md
> +![stack](./images/stack.png)
It looks like something went wrong with the rendering of this diagram. The font looks rather jagged...

2022-03-18 14:48 UTC, afrittoli commented on spec.md
> +CDEvents is a common specification for Continuous Delivery events. For more
I would not add this to the abstract.
We could link the README and primer docs in the overview below instead?

2022-03-18 14:57 UTC, afrittoli commented on README.md
> +#### Why not webhooks?
I'm not sure about this. I see webhooks as a way to deliver events, and I didn't know we recommended explicitly against them. CloudEvents include a spec for webhooks https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/http-webhook.md and they could be an interesting option in cases where authorization is required.

2022-03-25 13:27 UTC, m-linner-ericsson commented on README.md
> +pictures exemplifies.
Updated in 1ad4def

2022-03-25 13:28 UTC, m-linner-ericsson commented on images/stack.drawio
> +<mxfile host="Electron" modified="2022-03-09T14:09:43.285Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/16.5.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/
😃

2022-03-25 13:29 UTC, m-linner-ericsson commented on spec.md
> +CDEvents is a common specification for Continuous Delivery events. For more
Tried to make something in 1ad4def. Do you have any other good ideas?

2022-03-25 13:29 UTC, m-linner-ericsson commented on README.md
> +#### Why not webhooks?
Felt this was a bit on the edge so I removed it in 1ad4def

2022-03-25 13:30 UTC, m-linner-ericsson commented on README.md
> +![stack](./images/stack.png)
Hmm, that's not good. I however don't see the problem do you have some more info?

2022-03-25 16:02 UTC, afrittoli commented on README.md
> +![stack](./images/stack.png)
ok no worries, I don't want to block the PR on this - I see you included the source as well so I can also try to re-render it on my side

2022-03-25 16:03 UTC, afrittoli commented on spec.md
> +For an introduction see [README.md](README.md) and for  more background
NIT: extra space "for  more"

2022-03-25 16:03 UTC, afrittoli approved these changes
Thank for all the updates.
Just a nit but looks good to me

2022-03-30 12:15 UTC, m-linner-ericsson commented on spec.md
> +For an introduction see [README.md](README.md) and for  more background
```suggestion
For an introduction see [README.md](README.md) and for more background
```

2022-03-30 12:17 UTC, m-linner-ericsson commented on spec.md
> +For an introduction see [README.md](README.md) and for  more background
Fixed in 5bea30c

2022-03-30 12:55 UTC, afrittoli commented
@e-backmark-ericsson ok to merge?

2022-03-31 07:31 UTC, e-backmark-ericsson commented on primer.md
> +- [Design reflections](#design-reflections)
This ToC entry should be swapped with the previous line to match the actual content

2022-03-31 07:33 UTC, e-backmark-ericsson commented on README.md
> +The CDEvents protocol defines a vocabulary of events enabling tools to
As this is the first time "events" is mentioned in this document (which is probably the first document people read on CDEvents), I believe we should either link to a description of what an event is here, or add a sentence/paragraph about it inline

2022-03-31 07:36 UTC, e-backmark-ericsson requested changes
Just a very small change needed

2022-03-31 08:38 UTC, afrittoli commented on primer.md
> +- [Design reflections](#design-reflections)
You can run `./tools/update-toc.sh` to keep the ToCs updated - I should probably setup a CI job for that :)

2022-04-01 11:16 UTC, m-linner-ericsson commented on primer.md
> +- [Design reflections](#design-reflections)
Should be fixed in 610d408

2022-04-01 11:19 UTC, e-backmark-ericsson approved these changes

2022-04-01 11:20 UTC, merged