Introduce objects and subjects
cdevents/spec pull request #35
Opened 2022-03-22 15:48 UTC by afrittoli

Add the type system including objects.
Define subjects in the various protocol stages and rework the spec
accordingly.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

2022-03-22 16:57 UTC, afrittoli commented on spec.md
> +  - Keys are of type `String`. Valid keys can be defined by this spec
Convention / Best Practices for Key names e.g. CamelCase

2022-04-01 12:21 UTC, m-linner-ericsson reviewed
Hmm, got some worries here...

2022-04-01 12:21 UTC, m-linner-ericsson commented on core.md
> +| Field         | Mandatory ✅<br/>Permitted ⚪<br/>Not Permitted 🟥 |
(Exanding a bit on the above comment) I don't like this mental mapping. Isn't it easier that the subject object is the same for all events and then define in each event what fields should be part of it?

**Pipeline queued**
* Subject object
* Source (optional)

**Pipeline finished**
* Subject object
* Status
* Source (optional)

Pipeline finished example

```
{
   "version" : "draft",
   "id" : "A234-1234-1234",
   "source" : "/staging/tekton/",
   "type" : "dev.cdevents.taskrun.started",
   "timestamp" : "2018-04-05T17:31:00Z",
   "status": "finished",
   "subject" : {
      "type": "taskrun" 
      "id": "/namespace/taskrun-123",
      "name": "my-task",
      "URL": "/apis/tekton.dev/v1beta1/namespaces/default/taskruns/my-taskrun-123"
      }
   }
}
```

2022-04-20 14:57 UTC, e-backmark-ericsson reviewed
We need to settle on the base structure for the events, and I've provided some comments about that in this PR. I'm not saying that what is proposed is wrong, but I'd like to bring up alternative solutions in order to take a conscious decision on which way to go.

2022-04-20 14:57 UTC, e-backmark-ericsson commented on schemas/core/taskrunstarted.json
> +{
This schema doesn't fully match the example in for example cloudevents-binding.md, but before spending time on matching that we should decide on the top level structure of the data payload as is being discussed on the cloudevents-binding.md document

2022-04-20 14:57 UTC, e-backmark-ericsson commented on schemas/core/taskrunfininshed.json
> +    "required": [ "id", "taskName", "status"],
I believe that taskName shouldn't be required. The id field should be unique enough if I understand it correctly. Providing e.g. taskName and source in this event would be a duplication of data already provided through the started event, but as long as it is optional it might be fine.

2022-06-24 09:16 UTC, afrittoli commented on core.md
> +### `TaskRun`
The mapping there is not obvious to me. The doc there says:

> The table below is an attempt to create a mapping of common names for the various types of Pipeline Steps (the unit of work two degrees smaller than a Pipeline). 

We don't have anything in CDEvents to describe unit of work two degrees smaller than a Pipeline.
The doc continues with:

> (The effort of proposing a common vocabulary across CI/CD Tools and Technologies is not yet performed, but we'll use the most common term from the table above as the working term.)

I'm all in favour of aligning our names to the interop vocabulary, but I think we should do that once that's more settled, to avoid changing names several times. 
`TaskRun` is what we use today in the SDK and POC, so it's not something introduced in this PR

2022-06-24 09:17 UTC, afrittoli commented on core.md
> +| Field         | Mandatory ✅<br/>Permitted ⚪<br/>Not Permitted 🟥 |
ok, I'll update to try and address your comment

2022-06-24 09:37 UTC, afrittoli commented on spec.md
> +  - Keys are of type `String`. Valid keys can be defined by this spec
Done

2022-06-28 10:34 UTC, afrittoli commented on cloudevents-binding.md
> +The [CloudEvents `dataschema`](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema)
The schema version should be implied by the spec + event version. 

I'm a bit wary of mark this as mandatory, because that would signal clients that they should rely on it, and I think that should not be the case. 

The SDK can use the schema at development time, but I would not expect the SDK to always have to to fetch the schema at runtime from the `dataschema` field and validate the body against it.

2022-06-28 10:37 UTC, afrittoli commented on cloudevents-binding.md
> +Here is a full example of a CDEvents rendered to be transported via CloudEvents.
I think that even showing it together may be confusing because how it actually looks like depends on the cloudevents binding/mode selected. What I can do is provide a full example and clarify that that's for a specific binding/mode.

2022-06-28 10:38 UTC, afrittoli commented on cloudevents-binding.md
> +}
I will change this to cloudevents http binding binary mode instead of structured, to make it more clear.

2022-06-28 10:39 UTC, afrittoli commented on cloudevents-binding.md
> +   "subject" : "/namespace/taskrun-123",
copy/past mistake, thank you!

2022-06-29 09:12 UTC, afrittoli commented on cloudevents-binding.md
> +   "subject" : {
Updated this as discussed

2022-06-29 09:13 UTC, afrittoli commented on cloudevents-binding.md
> +{
Updated this as discussed

2022-06-29 10:03 UTC, afrittoli commented on schemas/core/taskrunfininshed.json
> +    "required": [ "id", "taskName", "status"],
I removed the schema for now, but I marked this as optional in the markdown doc

2022-06-29 10:04 UTC, afrittoli commented
> This was discussed on today's CDEvents Vocabulary meeting. Outcome:
> 
> Proposed event structure, the CDEvents context part or data payload: "meta": { "version" : "draft", "event_id" : "A234-1234-1234", "source" : "/staging/tekton/", "type" : "dev.cdevents.taskrun.started", (dev.cdevent.. "timestamp" : "2018-04-05T17:31:00Z" }, "subject": { "id": "/namespace/taskrun-123", "type": "taskrun", "content": { "URL": ... "pipelinerun": ... } }, _"extensions": [{ "name": <ext_name>, "content": ...} ], "links": [{ ... }]_
> 
> The part in _italics_ should not be added through this PR, but I just added it here as a reference since we discussed what further properties could be added on top level to the event structure later.
> 
> The reason for having so many sub objects in the structure is to simplify the SDK coding parts, and to have a clear json path extraction structure, like this: .data.
> 
> .<properties/content>.<content_properties>
> Examples of such json paths would then be: event.data.subject.id event.data.subject.content.URL
> 
> cc: @afrittoli , @m-linner-ericsson , @erkist

Updated accordingly

2022-06-29 10:24 UTC, afrittoli commented on schemas/core/taskrunstarted.json
> +{
Yes, I removed the schemas for now.

2022-06-29 10:25 UTC, afrittoli commented on core.md
> +### `PipelineRun Queued`
hopefully new the layout helps

2022-06-29 11:31 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +The [CloudEvents `dataschema`](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema)
hmm, even if the SDK will not use it to validate I think we should have it there so the reader can know what schema it was validated against. 

We currently have cases with Eiffel were we internally in Ericsson wants a stricter schema than the "vanilla" Eiffel one and in these cases the SDK should probably validate against it every time.

2022-06-29 11:50 UTC, afrittoli commented on cloudevents-binding.md
> +The [CloudEvents `dataschema`](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema)
Would it be fair to say than that the schema is mandatory if it's not the default one from the spec?
The schema will only be required in for structured mode, since in binary mode all CDEvents data will be in HTTP headers. It may be possible to specify a schema for the vendor specific content, but I would not have that mandatory.

2022-06-30 09:28 UTC, e-backmark-ericsson requested changes

2022-06-30 09:28 UTC, e-backmark-ericsson commented on spec.md
> +The specification is structured in three main parts:
Which is the third part?

2022-06-30 09:28 UTC, e-backmark-ericsson commented on spec.md
> +}}}}
I see several issues with this example:

- It differs from the structure proposed on May 3rd
- It's keys are not in CamelCase
- The "source" ("Source") key should be in the Context object instead of here
- It seems the URL assumes that the task run source is something in tekton, so I assume that "jenkins" and "tekton" should be switched in this example.
- The "Status" key should not be needed, as the predicate on the event type would reveal if the task is triggered, started, or finished.

```suggestion
{
  "Context": {
    "Source": "/tenant1/tekton"
    ... (other mandatory Context keys)
  },
  "Subject": {
    "Id": "my-taskrun-123",
    "Type": "TaskRun",
    "Content": {
      "Task": "my-task",
      "URL": "/apis/tekton.dev/v1beta1/namespaces/default/taskruns/my-taskrun-123"
      "PipelineRun": {
        "Id": "my-distributed-pipelinerun",
        "Source": "/tenant1/jenkins"
}}}}
```

2022-06-30 09:28 UTC, e-backmark-ericsson commented on spec.md
>  ## Context
So we should use "Context" instead of "Meta"? That's ok for me, but it's not inline with the suggestion in the comment from May 3rd.

2022-06-30 09:28 UTC, e-backmark-ericsson commented on spec.md
>  ## Context
All event attributes below should be CamelCase, right? And also the object keys within the examples below.

2022-06-30 09:28 UTC, e-backmark-ericsson commented on spec.md
>  ## Context
The "subject" ("Subject") below should be on heading level 2, just as "Context", right?

2022-06-30 15:52 UTC, e-backmark-ericsson requested changes
Added some more comments on top of my previous review today. I believe we might need a separate meeting to discuss these things once more...

2022-06-30 15:52 UTC, e-backmark-ericsson commented on core.md
> +Core events are at the lower level of abstraction in the dictionary: they describe the status execution, but they don't include any semantic about the function of the execution itself. These events a
```suggestion
Core events are at the lower level of abstraction in the dictionary: they describe the status of an execution, but they don't include any semantic about the function of the execution itself. These events are generated by [pipeline orchestration engines](https://landscape.cd.foundation/card-mode?category=ci-pipeline-orchestration&grouping=category).
```

2022-06-30 15:52 UTC, e-backmark-ericsson commented on core.md
> +| Status | `Enum` | Status of a finished `PipelineRun` | `success`, `error` or `failure`|
I know that we've had "Status" defined here since earlier, but that term is confusing to me. Status of a pipeline execution sounds like a snapshot status of an ongoing pipeline (for example "30% done"), so "Result" would probably be more appropriate. Or we could use the same terminology as Eiffel does, which is to provide an "Outcome" object containing a "Conclusion" (enum) and an optional "Description" (free-text human readable string): [Eiffel ActivityFinished outcome](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityFinishedEvent.md#dataoutcome)

```suggestion
| Result | `Enum` | Result of a finished `PipelineRun` | `success`, `error` or `failure`|
```

2022-06-30 15:52 UTC, e-backmark-ericsson commented on core.md
> +| Status | `Enum` | Status of a finished `TaskRun` | `success`, `error` or `failure`|
Inline with my suggestion for PipelineRun.Status above:

```suggestion
| Result | `Enum` | Status of a finished `TaskRun` | `success`, `error` or `failure`|
```

2022-06-30 15:52 UTC, e-backmark-ericsson commented on core.md
> +## Subjects
On a closer thought on this, I think the use of Subjects is still confusing here. The subject is e.g. PipelineRun, and it should have certain attributes identifying it. Those attributes are for a pipeline probably Id and Name, where Name might be optional. Then for each subject AND predicate there are a number of additional attributes that could/should be included in the events, such as URL for PipelineRun Started and Finished for example. Such attributes don't fit in the Subject object to me, but should rather be placed in a "Predicate" object in the event, if we should follow that naming structure. If so, the Subject and Predicate objects could look like this:
```json
"Subject": {
  "Id": ...,
  "Type": "taskrun",
  "Content": {
    "Name": ...
  },
},
"Predicate": {
  "type": "finished",
  "content": {
    "URL": ...,
    "Result": ...
}}
```
With that, the Subject object in the schema would be identical for all events for the same object, but the Predicate object would differ for different predicates. And when describing those varying Predicate object attributes in a table similar to the Subject table below, there could be an additional column for each Predicate type where it could be stated if the attribute is mandatory or optional for the specific predicate. With that we would not need to duplicate the attribute information to separate tables further down on this page.

2022-07-04 10:03 UTC, afrittoli commented on core.md
> +## Subjects
If I understand your comment correctly, you would like to separate the "static" definition of a subject from its "dynamic" or "runtime" part. I think I understand the idea, but I'm also concerned that the line of separation may not be so clear for other subjects.
My feeling is that this separation adds complexity and more constraints like that in CDEvents, but I don't see a clear value in return. 
If the main value is to avoid replicating field definition in the spec I would say it's not worth it, that's something we can solve via automation.

2022-07-04 10:12 UTC, afrittoli commented on core.md
> +Core events are at the lower level of abstraction in the dictionary: they describe the status execution, but they don't include any semantic about the function of the execution itself. These events a
Fixed

2022-07-04 10:37 UTC, afrittoli commented on spec.md
>  ## Context
Another thing to maybe consider is that all event types are lower case, so we fully inconsistent across the spec :D

2022-07-04 11:43 UTC, e-backmark-ericsson commented on spec.md
>  ## Context
I don't have a strong opinion whether we should use upper camel case or lower camel case, but we should be consistent, both in our spec, in the primer, and in our event examples. We could have different standards for event type names and the keys within them. And of course some bindings and SDK languages might require a certain type of casing and then we should have exceptions for those.
To avoid ambiguation I'd prefer if we state "UpperCamelCase" or "lowerCamelCase" in our naming conventions, as "camel case" is ambiguous".

2022-07-04 14:57 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +The [CloudEvents `dataschema`](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema)
Not sure I follow here, but will not fight for it. Just a notice that I think it would be good to have a schema to always refer to.

2022-07-04 15:12 UTC, m-linner-ericsson commented
@afrittoli I don't have any more comments currently

2022-07-06 20:03 UTC, afrittoli commented on core.md
> +## Subjects
This will be tracked in a separate issue / PR

2022-07-07 05:52 UTC, e-backmark-ericsson commented on core.md
> +## Subjects
Yes, in #51

2022-07-07 05:59 UTC, e-backmark-ericsson commented on core.md
> +| [`pipelineRun`](#pipelinerun) | An instance of a *pipeline* | [`Queued`](#pipelinerun-queued), [`started`](#pipelinerun-started), [`finished`](#pipelinerun-finished)|
```suggestion
| [`pipelineRun`](#pipelinerun) | An instance of a *pipeline* | [`queued`](#pipelinerun-queued), [`started`](#pipelinerun-started), [`finished`](#pipelinerun-finished)|
```

2022-07-07 06:00 UTC, e-backmark-ericsson commented on core.md
> +| url | `URI` | url to the `pipelineRun` | `https://dashboard.org/namespace/pipelinerun-1234`, `https://api.cdsystem.com/namespace/pipelinerun-1234` | ⚪ |
Duplicated line
```suggestion
```

2022-07-07 06:06 UTC, e-backmark-ericsson requested changes
Just two minor typos, then it's fine.

2022-07-07 09:31 UTC, afrittoli commented on core.md
> +| [`pipelineRun`](#pipelinerun) | An instance of a *pipeline* | [`Queued`](#pipelinerun-queued), [`started`](#pipelinerun-started), [`finished`](#pipelinerun-finished)|
Fixed

2022-07-07 09:33 UTC, afrittoli commented on core.md
> +| url | `URI` | url to the `pipelineRun` | `https://dashboard.org/namespace/pipelinerun-1234`, `https://api.cdsystem.com/namespace/pipelinerun-1234` | ⚪ |
Nice catch, this should have been `outcome` instead

2022-07-07 09:50 UTC, e-backmark-ericsson approved these changes

2022-07-07 09:59 UTC, merged