Format source code events same as core
cdevents/spec pull request #52
Opened 2022-07-07 14:16 UTC by afrittoli

Reformat the source code version control stage page to match what
done for the core stage. No spec changes.

Part of #13

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

2022-07-07 14:51 UTC, e-backmark-ericsson requested changes
Small typos

2022-07-07 14:51 UTC, e-backmark-ericsson commented on source-code-version-control.md
> +- Event Type: __`dev.cdevents.repository.created`__
```suggestion
- Event Type: __`dev.cdevents.repository.modified`__
```

2022-07-07 14:51 UTC, e-backmark-ericsson commented on source-code-version-control.md
> +- Event Type: __`dev.cdevents.repository.created`__
```suggestion
- Event Type: __`dev.cdevents.repository.deleted`__
```

2022-07-07 16:04 UTC, afrittoli commented on source-code-version-control.md
> +- Event Type: __`dev.cdevents.repository.created`__
Nice catch, thank you!

2022-07-07 16:04 UTC, afrittoli commented on source-code-version-control.md
> +- Event Type: __`dev.cdevents.repository.created`__
Nice catch, thank you!

2022-07-08 05:08 UTC, e-backmark-ericsson approved these changes

2022-07-08 07:19 UTC, merged