Add CDEvents binary mode specification
cdevents/spec pull request #54
Opened 2022-07-26 14:53 UTC by afrittoli

Add the CDEvents binary mode spec and example to the cloudevents
binding document. Remove the limitation to HTTP Binary mode as
most CloudEvents bindings suppport binary mode, not only HTTP.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

2022-07-27 09:01 UTC, m-linner-ericsson requested changes
As i read the specification of e.g. https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md I think we are implementing it wrong.

2022-07-27 14:07 UTC, afrittoli commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
> I would say this is invalid. E.g if I read https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md#3131-http-header-names it says
> 
> > Except where noted, all CloudEvents context attributes, including extensions, MUST be mapped to HTTP headers with the same name as the attribute name but prefixed with `ce-`.
> 

This part of the spec describes how CloudEvents context attributes and extensions should be represented. 
This does not apply to CDEvents content, which is neither a cloudevents extensions nor cloudevents context.

> Also reading https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md#design-goals
> 
> > CloudEvents, at its core, defines a set of metadata, called "context attributes", about the event being transferred between systems, and how those pieces of metadata should appear in that message. This metadata is meant to be the minimal set of information needed to route the request to the proper component and to facilitate proper processing of the event by that component. So, while this might mean that some of the application data of the event itself might be duplicated as part of the CloudEvent's set of attributes, this is to be done solely for the purpose of proper delivery, and processing, of the message. Data that is not intended for that purpose should instead be placed within the event (`data`) itself
> 
> If we want them for routing we should duplicate out that information.

The reason for duplication is to put data in the headers if it is only available in the payload otherwise.
In binary mode relevant data is in headers already, so strictly speaking there is no need for duplication - but I would be open to have information that is `ce-` headers repeated in `cdevents-` header for better separation.

> 
> I would suggest to skip the whole binary/structured thing and refer the to the spec of the transfer protocol instead.

I disagree on this, the CloudEvents binary/structured spec does not cover a binary mode for CDEvents, so removing this would mean not have this feature - and I think we really need it for ease of adoption.

2022-07-27 14:12 UTC, afrittoli commented on cloudevents-binding.md
> +`ce-` headers. The subject `id` is already available in `ce-subject` and not
Ah, nice catch, I will update that.
I guess we might need to support different names for different bindings at CDEvents level too, but I was really hoping to avoid that.

2022-07-27 14:20 UTC, afrittoli commented on cloudevents-binding.md
> +      "timestamp" : "2018-04-05T17:32:00Z",
I don't see any use case where we would use the CloudEvents structured mode, especially in the example, as it mixes the CloudEvents and CDEvents JSON into one, which in my opinion is much harder to read.

We could consider CloudEvents structured if we wanted in future to keep introduce support for CloudEvents batch mode, but otherwise I would suggests that CDEvents assumes CloudEvents binary mode is the default (it's the default mode in the CloudEvents SDK as well).

For me valid combinations at this stage are:
1. CloudEvents binary with CDEvents structured: this is the most natural to me as CDEvents carries payload data, so the payload seems the natural place for it
2. CloudEvents binary with CDEvents binary: this is very helpful to introduce CDEvents for producers that already use CloudEvents as their events will be consumable by both existing consumers and new CDEvents consumers

What I proposed for the spec is to use (1) by default for examples, for readability purposes, and (2) only in CDEvents binary mode specific examples, since the unstructured HTTP headers seems harder to parse.

2022-07-29 14:24 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
I must be missing something as I really think we creating more problems by having a binary mode for CDEvents. The whole idea with CloudEvents is that you don't need to think about that part and in my head it creates confusion. 

Further the CDEvents spec says:

>CloudEvents extensions that define their own attributes MAY define a secondary mapping to HTTP headers for those attributes, especially if specific attributes need to align with HTTP features or with other specifications that have explicit HTTP header bindings. Note that these attributes MUST also still appear in the HTTP message as HTTP headers with the ce- prefix as noted in [HTTP Header Names](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md#3131-http-header-names).

The only reason for sending extra headers is for specific HTTP features which we are not after.

**Conclusion** I would need some explanation of why we would need the CDEvents binary mode. As I see it we should not have it.

* Creates confusion
* CloudEvents should take care of that part for us

2022-07-29 14:33 UTC, afrittoli commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
Follow-up on this, after having a conversation with the the CloudEvents folks I can confirm that extra headers would not work as a CloudEvents router would drop them. The way I understand it is that it breaks the encapsulation.
The only option to use headers would be by defining CloudEvents extensions (which is what the go SDK does today), but I fear that may become too much (too many extensions).

2022-07-29 14:37 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
Yes I think that would create too many extensions. Why go with [KISS](https://en.wikipedia.org/wiki/KISS_principle) do the simplest possible in the beginning.

2022-07-29 14:38 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +      "timestamp" : "2018-04-05T17:32:00Z",
I find the structured mode easier to read and provides more generic examples. If you look at https://github.com/serverlessworkflow/specification/blob/main/examples/README.md others seems to use the structured mode for examples.

I don't think we should focus to much on the HTTP examples as that is only one part of what CloudEvents provide. I think we should focus on the content of what our events should give and use CloudEvents for the transport parts.

2022-07-29 14:42 UTC, afrittoli commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
> **Conclusion** I would need some explanation of why we would need the CDEvents binary mode. As I see it we should not have it.

The reason I started considering binary mode it to make it make it easier to adopt CDEvents where CloudEvents are already in use, but with a vendor payload. If CDEvents could use the same payload as existing application events, then we could support a setup with mixed consumers, some that migrated to CDEvents and some that didn't, since the same message would be usable by both.
> 
> * Creates confusion
> * CloudEvents should take care of that part for us

CloudEvents doesn't help with the problem of mixed consumers specifically. 
The only alternative I have mind for this problem is to support producer that can send multiple message types at once.

2022-08-03 08:56 UTC, m-linner-ericsson commented on cloudevents-binding.md
> +by `cdevents-`, except for `type` and `source` which are already available as
> The reason I started considering binary mode it to make it make it easier to adopt CDEvents where CloudEvents are already in use, but with a vendor payload. If CDEvents could use the same payload as existing application events, then we could support a setup with mixed consumers, some that migrated to CDEvents and some that didn't, since the same message would be usable by both.

Not sure I follow here. If they are sending cloud events today I guess the listeners would filter out our events as we have a different `type`. I don't understand why we would need to add in extra stuff.

Also when it comes to the *structured/binary* discussion we should be aware that in e.g. https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/avro-format.md they don't have both, only one.

2022-08-18 14:02 UTC, afrittoli commented
We're not going to use binary mode, as discussed during the working group.

2022-08-18 14:02 UTC, closed without merging