Add change to the artifact packaged event
cdevents/spec pull request #73
Opened 2022-10-07 12:36 UTC by afrittoli

# Changes

The artifact packaged event is typically produced by the build process, and should provide details about the source the artifact was built from.

While working on the artifact change field, I realised that for the change and branch events the id + source combination should also contain the repository details, otherwise it wouldn't uniquely identify a change.

I added a note in the change/branch event section and updated the examples accordingly. I think there is still value in have a repository field in those events, but I marked it as optional (it was mandatory before).

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer.md#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2022-10-09 09:08 UTC, erkist approved these changes
I have nit-picky comments only, feel free to ignore

2022-10-09 09:08 UTC, erkist commented on continuous-integration-pipeline-events.md
> +| change | `object`        | The top change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`,
The term "top change" is a bit ambiguous to me. Maybe something like "The change (tag, commit, revision etc.) of the repository which was used to build the artifact"?

2022-10-09 09:08 UTC, erkist commented on primer.md
> +We plan to extend the data model to more complex scenarios in upcoming releases.
to more -> to support more

2022-10-09 09:08 UTC, erkist commented on primer.md
> +This data model is somewhat limiting, but is has allowed us to put more focus
This -> The current
limiting -> limited? (limiting is fine too)

2022-10-10 07:41 UTC, e-backmark-ericsson requested changes
I'd like to see some minor adjustments before approving this PR

2022-10-10 07:41 UTC, e-backmark-ericsson commented on continuous-integration-pipeline-events.md
> +| change | `object`        | The top change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`,
I agree with Erik. The examples show specific commit ids or tags, and that is what I believe would be checked out when (re)building this artifact. I don't see the need to say "top change" since "change" would be enough. It could be good to clarify that such a change could be based on (and thus include) changes that where not built into the previous artifact, but I believe that would be obvious to the consumers, or?

```suggestion
| change | `object`        | The change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`, `{"id": "feature1234", "source": "my-git.example/an-org/a-repo"}` |
```

2022-10-10 07:41 UTC, e-backmark-ericsson commented on primer.md
> +each artifact is build from a single repository and each service is deployed
```suggestion
each artifact is built from a single repository and each service is deployed
```

2022-10-10 10:07 UTC, afrittoli commented on continuous-integration-pipeline-events.md
> +| change | `object`        | The top change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`,
Uhm, this makes we wonder if we in future we should use "revision" as field name.
I think for 0.1 it's fine to use change as it matches the name of the change events, but perhaps in future we could use a revision field instead

2022-10-10 10:09 UTC, afrittoli commented on continuous-integration-pipeline-events.md
> +| change | `object`        | The top change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`,
Fixed

2022-10-10 10:09 UTC, afrittoli commented on primer.md
> +We plan to extend the data model to more complex scenarios in upcoming releases.
Good catch, thank you. Fixed now.

2022-10-10 10:09 UTC, afrittoli commented on primer.md
> +This data model is somewhat limiting, but is has allowed us to put more focus
done

2022-10-10 10:11 UTC, afrittoli commented on continuous-integration-pipeline-events.md
> +| change | `object`        | The top change of the repository from which the artifact has been built | `{"id": "527d4a1aca5e8d0df24813df5ad65d049fc8d312", "source": "my-git.example/an-org/a-repo"}`,
Thank you! Fixed

2022-10-10 10:11 UTC, afrittoli commented on primer.md
> +each artifact is build from a single repository and each service is deployed
Thank you! Fixed

2022-10-10 10:27 UTC, e-backmark-ericsson approved these changes

2022-10-10 10:36 UTC, merged