Document how to adopt and adapt CDEvents
cdevents/spec pull request #77
Opened 2022-10-13 15:30 UTC by afrittoli

# Changes

Document a series of scenarios about adopting CDEvents producer and consumer side. Describe how to adapt CDEvents with customData and how to contribute new fields and events to the community.

Document declarative vs. imperative events and the subscriber model.

Fixes: #66
Fixes: #42

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer.md#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

2022-10-13 20:07 UTC, xibz reviewed
@afrittoli Awesome job on this! I really like the level of detail of each section. I had several comments, but this could be due to not understanding the full picture for the particular implementation.

2022-10-13 20:07 UTC, xibz commented on primer.md
> +This is approach is certainly valid to build a proof-of-concept or experiment
I dont know how I feel about this approach. Maybe if I had some usecases, but what doesn't make much sense to me is users would need to log the necessary information to even have it ingested and then have this agent produce the events. If users are already changing these logs, why not just use the SDK to produce the events directly?

2022-10-13 20:07 UTC, xibz commented on primer.md
> +Similar to the [previous case](#external-event-producer), incoming events may be
Similar to the comment above, wouldn't the adapter need to have some context to what the event is? Why couldn't this just be a handler injected in the HTTP client's instead? It doesn't need to be external, from what I am gathering.

2022-10-13 20:07 UTC, xibz commented on primer.md
> +In a variation of the previous two producer scenarios, the tool produces only
This makes it sound like it needs to be internal, but like above, we could have a HTTP handler that lives inside the service deal with this right?

2022-10-13 21:21 UTC, afrittoli commented on primer.md
> +A behavior similar to that of imperative events can be achieved by moving part
Yes, I tend to associate imperative with p2p and API calls as well, however there are systems - like Keptn - that do imperative via events. In Keptn one defines the sequence of events like build test deploy and Keptn orchestrates that via events. It sends a "do a build" event, or "do a deployment" event, and one or more systems may take the job and do it an report back through a the original context ID provided by Keptn.

2022-10-13 21:21 UTC, afrittoli commented on primer.md
> +  consider proposing the new field name for the vocabulary as well.
Sounds good, will do

2022-10-13 21:30 UTC, afrittoli commented on primer.md
> +This is approach is certainly valid to build a proof-of-concept or experiment
These scenarios are mostly provided as interim steps towards native support of CDEvents.

If I receive events from a source that I don't control, I can use an adapter to convert them to CDEvents. Once the source can send CDEvents I won't need the adapter any longer.

If I'm building a POC, rather than changing the tool code and adding eventing capabilities, I can watch an output and send events based on that. 

In some cases, it can be used as a long-term strategy. In Tekton for instance we are building a cloudevent / cdevents controller that watches Tekton resources and sends events based on their condition changes. This offloads the job of sending events from the core controller and allows the development of a reacher event-specific feature set.

Other examples could be simply CLI tools. For those I would not add eventing capabilities, but I could send the event directly from a shell script that executes the CLI tool.

I hope this clarifies a bit, but happy to discuss further on this.

2022-10-13 21:33 UTC, afrittoli commented on primer.md
> +Similar to the [previous case](#external-event-producer), incoming events may be
The lack of context is the main gotcha with this kind of external adapters approaches, I should do a better job of expressing that in the doc. Similar to the case above, if one does not control the source, adapting is a good interim solution. 

I can adapt GitHub webhooks to CDEvents for instance.

2022-10-13 21:38 UTC, afrittoli commented on primer.md
> +In a variation of the previous two producer scenarios, the tool produces only
The adapter can leave in many different places, inside the producer, in front of the producer, it can be in the "middle", subscribe to events and resubmit them for whoever is listening (like in this scenario).

Where it sits depends on the kind of control we have on the event producers and consumers, and other factors too. For instance, the adapter could be a single component that receives N kinds of events and produces CDEvents out of each.

2022-10-13 22:00 UTC, xibz commented on primer.md
> +A behavior similar to that of imperative events can be achieved by moving part
Ah, right, Temporal also behaves this way except a little more vaguely. Okay, cool, I think we should also highlight imperative being a valid use case for p2p since we call out not doing it, but it may make sense for this particular instance.

2022-10-13 22:00 UTC, xibz commented on primer.md
> +This is approach is certainly valid to build a proof-of-concept or experiment
Hmm, yea, so the only issue that I have with this is it seems a little hand wavy to me, because in order for an adapter to work some context is needed from the application, still, you can't just send the same payload, and expect the adapter to know what/how to make a CdEvent from it, unless you had a unique adapter for every user that knows implicitly how to deal with the payloads, and if users are building this adapter, at that point I'd say just use CdEvents directly. I think that's more of what I am getting at. Then, if there are plans to have a single adapter, having some context is needed, which again would require the user's service to change to send the necessary context. So I am just trying to understand how do you envision this being an interim step, because those are the only ways I can see an adapter working, unless I completely missed something. Which is totally possible!

2022-10-13 22:00 UTC, xibz commented on primer.md
> +Similar to the [previous case](#external-event-producer), incoming events may be
Similar response above

2022-10-13 22:00 UTC, xibz commented on primer.md
> +In a variation of the previous two producer scenarios, the tool produces only
Right, I guess having it a little ambiguous doesn't hurt, but I think the docs makes it seem like this adapter is a separate thing, especially from the diagrams. So I just dont want users to get the wrong idea.

2022-10-14 09:10 UTC, afrittoli commented on primer.md
> +A behavior similar to that of imperative events can be achieved by moving part
ok, I will expand on this one.
What we discussed in the past is that we may include imperative events in future as a dedicated subgroup of the spec, but that may be something for the next release - if someone takes ownership of specifying them.

2022-10-14 09:29 UTC, afrittoli commented
Page rendered with images available at https://github.com/afrittoli/cdevents-spec/blob/adopting_cdevents/primer.md

2022-10-14 10:41 UTC, afrittoli commented on primer.md
> +This is approach is certainly valid to build a proof-of-concept or experiment
You can have an adapter that is flexible and let you define rules for every user.
The CDEvents data model is still rather thin, so it's not so difficult to find the required data already in there.

The CDEventer tool that I created for the DORA PoC works together with Tekton to adapt existing events and webhook into CDEvent - checkout the [architecture diagram](https://github.com/afrittoli/cdeventer#architecture).
In the POC I used it to adapt events from Gitea, from Azure container registry and from the Knative API source, and I can do that by mapping input values into CDEvents fields.

Ultimately I would like Gitea and other SCM systems to produce CDEvents directly. The same goes for various container registries and other sources of events, but this worked well as an interim solution for the PoC.

I tried using docker hub webhooks and they only provided me with the image tag (no sha) so it didn't work for the POC. This is an example of why having the CDEvents data model at the source is better of course, for the POC I had to pick a different container registry.

2022-10-14 13:52 UTC, afrittoli commented on primer.md
> +In a variation of the previous two producer scenarios, the tool produces only
Heh, diagrams did not intend to be ambiguous - when the adapter is a box on its own it is separate from producer / consumer.

2022-10-16 14:48 UTC, erkist commented on primer.md
> +With imperative events we intend events that are sent with the intent to trigger
Consider moving this below the definition of "declarative events" below, so users who are reading "too fast" still understand that CDEvents are declarative.

2022-10-16 14:48 UTC, erkist commented on primer.md
> +With imperative events we intend events that are sent with the intent to trigger
intend -> are referring to

2022-10-16 14:48 UTC, erkist commented on primer.md
> +event will be used on the receiving side.
(or even who will receive it)

2022-10-16 14:48 UTC, erkist commented on primer.md
> +Adding a new field to existing an existing CDEvent type is a backward compatible
I guess this depends on who's perspective we take? Adding a mandatory field to a CDEvent wouldn't be backwards compatible for the senders, right?
For the receivers, having this backwards compatible implies that whatever strategy they use for "parsing" the CDEvent (from for instance JSON) must ignore keys it doesn't recognize. If this is a requirement on receivers, maybe we can state it somewhere?

2022-10-16 14:48 UTC, erkist commented on primer.md
> +  vocabulary][sig-interop-vocabulariy] if a standard name exists. If not
vocabulariy -> vocabulary

2022-10-16 14:48 UTC, erkist commented on primer.md
> +CDEvents is a new specifications, but neither CloudEvents not events in general
not -> nor

2022-10-17 09:29 UTC, e-backmark-ericsson requested changes
Very well written! I agree with the comments mentioned by others and there are a few more linguistic bugs, but not far from being accepted :)

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +![watcher-producer](images/watcher-producer.svg)
We could benefit from "greying out" the consumer part of this picture, since there might be multiple consumer scenarios relevant for this producer scenario.
And it could be relevant to include the Cloudevents symbol in all pictures on this page, to not confuse the readers.

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +![adapter](images/adapter.svg)
Same comment as for previous picture

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +![multiple-produced](images/multiple-produced.svg)
Same as for previous picture
And I don't think the "Event" keyword under the Cloudevents symbol adds any value. If it should be kept I believe the same should be used on the consuming side, but I prefer to omit the "Event" text completely here.

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +![original-adapter](images/original-adapter.svg)
Here the picture could be kept as-is, since both producer and consumer-side are discussed in the text, but I again think that the "Event" text should be omitted. And all Cloudevents symbols should have equal size.

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +#### Multiple event formats
```suggestion
#### Multiple event formats produced
```
(inline with my suggestion on multiple consumed below)

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +#### Multiple received
```suggestion
#### Multiple event formats consumed
```

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +event will be used on the receiving side.
@erkist , Yes I like that amendment!

2022-10-17 09:29 UTC, e-backmark-ericsson commented on primer.md
> +Adding a new field to existing an existing CDEvent type is a backward compatible
Yes, I think we should expand the statement saying that it is backwards compatible from consumer point of view, and assuming that consumers neglect additional fields that they don't understand.

2022-10-17 09:59 UTC, afrittoli commented on primer.md
> +With imperative events we intend events that are sent with the intent to trigger
sounds good

2022-10-17 10:13 UTC, afrittoli commented on primer.md
> +![watcher-producer](images/watcher-producer.svg)
I split the scenarios into producer ones and consumer ones because they can be combined in different ways, I can make that more explicit in the first paragraph. 

The colour of the consumer boxes has its relevance though since not all producer scenarios apply to consumer ones, but I can try to find a way to highlight this visually more. I'll try the greying option and see how it looks.

2022-10-17 10:17 UTC, afrittoli commented on primer.md
> +![multiple-produced](images/multiple-produced.svg)
I started with the word "event" only because it doesn't have to CloudEvents. 
With CloudEvents it's easier because one can have the same broker passing CDEvents and CloudEvents around which is why I added a small CloudEvent logo there, but it's not obvious from the picture.

Perhaps I should simply remove CloudEvents from the picture, also to avoid fostering confusion between CloudEvents and CDEvents.

2022-10-17 10:25 UTC, e-backmark-ericsson reviewed
A missing hyphen

2022-10-17 10:25 UTC, e-backmark-ericsson commented on primer.md
> +    - [Consumer side adapters](#consumer-side-adapters)
```suggestion
    - [Consumer-side adapters](#consumer-side-adapters)
```

2022-10-17 10:27 UTC, e-backmark-ericsson commented on primer.md
> +Adding a new field to existing an existing CDEvent type is a backward compatible
It could be enough to add a link here to the versioning section, so we don't duplicate information unnecessarily

2022-10-17 10:30 UTC, e-backmark-ericsson commented on primer.md
> +![multiple-produced](images/multiple-produced.svg)
Well, since these pictures are just examples anyway, I see no issue with exemplifying using Cloudevents in them. But if some should contain the term "Event" and some not, and if some should be larger than others that needs to be explained in some way in a legend or similar I think.

2022-10-18 12:40 UTC, e-backmark-ericsson approved these changes

2022-10-19 08:55 UTC, afrittoli commented
During the last WG, we agreed to merge the PR as it is now.
@xibz I'm not sure if I addressed/answered all of your concerns yet, so I'd like to continue the conversation and evolve this incrementally.

2022-10-19 08:59 UTC, merged

2022-10-20 00:28 UTC, xibz commented
> I'm not sure if I addressed/answered all of your concerns yet, so I'd like to continue the conversation and evolve this incrementally.

Yea, I think you got most of what I wanted. Been super busy with prepping for Spinnaker Summit! But yea, Im sure this is going to evolve incrementally either way :)